object Form15: TForm15
  Left = 298
  Top = 178
  Width = 321
  Height = 383
  Caption = #33258#23450#20041#26434#39033#37319#36141#25253#34920'('#22269#20869')'
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
  object ppDB0070: TppDBPipeline
    DataSource = DM.DataSource1
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB0070'
    Left = 128
    Top = 110
    object ppDB0070ppField1: TppField
      Alignment = taRightJustify
      FieldAlias = 'rkey'
      FieldName = 'rkey'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 0
      Position = 0
    end
    object ppDB0070ppField2: TppField
      FieldAlias = 'po_number'
      FieldName = 'po_number'
      FieldLength = 15
      DisplayWidth = 15
      Position = 1
    end
    object ppDB0070ppField3: TppField
      FieldAlias = 'PO_REV_NO'
      FieldName = 'PO_REV_NO'
      FieldLength = 5
      DisplayWidth = 5
      Position = 2
    end
    object ppDB0070ppField4: TppField
      FieldAlias = 'po_date'
      FieldName = 'po_date'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 3
    end
    object ppDB0070ppField5: TppField
      Alignment = taRightJustify
      FieldAlias = 'status'
      FieldName = 'status'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 4
    end
    object ppDB0070ppField6: TppField
      FieldAlias = 'PO_TYPE'
      FieldName = 'PO_TYPE'
      FieldLength = 1
      DisplayWidth = 1
      Position = 5
    end
    object ppDB0070ppField7: TppField
      Alignment = taRightJustify
      FieldAlias = 'PURCHASE_ORDER_TYPE'
      FieldName = 'PURCHASE_ORDER_TYPE'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 10
      Position = 6
    end
    object ppDB0070ppField8: TppField
      FieldAlias = 'empl_code'
      FieldName = 'empl_code'
      FieldLength = 5
      DisplayWidth = 5
      Position = 7
    end
    object ppDB0070ppField9: TppField
      FieldAlias = 'employee_name'
      FieldName = 'employee_name'
      FieldLength = 16
      DisplayWidth = 16
      Position = 8
    end
    object ppDB0070ppField10: TppField
      FieldAlias = 'code'
      FieldName = 'code'
      FieldLength = 5
      DisplayWidth = 5
      Position = 9
    end
    object ppDB0070ppField11: TppField
      FieldAlias = 'supplier_name'
      FieldName = 'supplier_name'
      FieldLength = 30
      DisplayWidth = 30
      Position = 10
    end
    object ppDB0070ppField12: TppField
      FieldAlias = 'v_status'
      FieldName = 'v_status'
      FieldLength = 10
      DisplayWidth = 10
      Position = 11
    end
    object ppDB0070ppField13: TppField
      FieldAlias = 'v_type'
      FieldName = 'v_type'
      FieldLength = 4
      DisplayWidth = 4
      Position = 12
    end
    object ppDB0070ppField14: TppField
      Alignment = taRightJustify
      FieldAlias = 'shipping_cost'
      FieldName = 'shipping_cost'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 13
    end
    object ppDB0070ppField15: TppField
      Alignment = taRightJustify
      FieldAlias = 'MISC_CHARGE'
      FieldName = 'MISC_CHARGE'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 14
    end
    object ppDB0070ppField16: TppField
      Alignment = taRightJustify
      FieldAlias = 'SUPP_FAC_ADD_PTR'
      FieldName = 'SUPP_FAC_ADD_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 15
    end
    object ppDB0070ppField17: TppField
      Alignment = taRightJustify
      FieldAlias = 'PAYMENT_TERMS'
      FieldName = 'PAYMENT_TERMS'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 16
    end
    object ppDB0070ppField18: TppField
      Alignment = taRightJustify
      FieldAlias = 'sub_total'
      FieldName = 'sub_total'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 17
    end
    object ppDB0070ppField19: TppField
      Alignment = taRightJustify
      FieldAlias = 'EXCHANGE_RATE'
      FieldName = 'EXCHANGE_RATE'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 18
    end
    object ppDB0070ppField20: TppField
      FieldAlias = 'fob'
      FieldName = 'fob'
      FieldLength = 15
      DisplayWidth = 15
      Position = 19
    end
  end
  object DataSource2: TDataSource
    DataSet = DM.AQ0493
    Left = 97
    Top = 250
  end
  object ppDB493: TppDBPipeline
    DataSource = DataSource2
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB493'
    Left = 128
    Top = 250
    object ppDB493ppField1: TppField
      FieldAlias = 'Company_Name'
      FieldName = 'Company_Name'
      FieldLength = 50
      DisplayWidth = 50
      Position = 0
    end
    object ppDB493ppField2: TppField
      FieldAlias = 'ship_address'
      FieldName = 'ship_address'
      FieldLength = 50
      DisplayWidth = 50
      Position = 1
    end
    object ppDB493ppField3: TppField
      FieldAlias = 'Company_Icon'
      FieldName = 'Company_Icon'
      FieldLength = 0
      DataType = dtBLOB
      DisplayWidth = 10
      Position = 2
      Searchable = False
      Sortable = False
    end
    object ppDB493ppField4: TppField
      FieldAlias = 'SITE_INFO_ADD_1'
      FieldName = 'SITE_INFO_ADD_1'
      FieldLength = 50
      DisplayWidth = 50
      Position = 3
    end
    object ppDB493ppField5: TppField
      FieldAlias = 'SITE_INFO_ADD_2'
      FieldName = 'SITE_INFO_ADD_2'
      FieldLength = 50
      DisplayWidth = 50
      Position = 4
    end
    object ppDB493ppField6: TppField
      FieldAlias = 'SITE_INFO_ADD_3'
      FieldName = 'SITE_INFO_ADD_3'
      FieldLength = 50
      DisplayWidth = 50
      Position = 5
    end
    object ppDB493ppField7: TppField
      FieldAlias = 'SITE_INFO_PHONE'
      FieldName = 'SITE_INFO_PHONE'
      FieldLength = 30
      DisplayWidth = 30
      Position = 6
    end
  end
  object ppDB70: TppDBPipeline
    DataSource = DM.DataSource2
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB70'
    Left = 128
    Top = 80
    object ppDB70ppField1: TppField
      Alignment = taRightJustify
      FieldAlias = 'RKEY'
      FieldName = 'RKEY'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 10
      Position = 0
    end
    object ppDB70ppField2: TppField
      FieldAlias = 'PO_NUMBER'
      FieldName = 'PO_NUMBER'
      FieldLength = 15
      DisplayWidth = 15
      Position = 1
    end
    object ppDB70ppField3: TppField
      Alignment = taRightJustify
      FieldAlias = 'CSI_USER_POINTER'
      FieldName = 'CSI_USER_POINTER'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 2
    end
    object ppDB70ppField4: TppField
      Alignment = taRightJustify
      FieldAlias = 'EMPLOYEE_POINTER'
      FieldName = 'EMPLOYEE_POINTER'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 3
    end
    object ppDB70ppField5: TppField
      Alignment = taRightJustify
      FieldAlias = 'SUPPLIER_POINTER'
      FieldName = 'SUPPLIER_POINTER'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 4
    end
    object ppDB70ppField6: TppField
      Alignment = taRightJustify
      FieldAlias = 'SUPP_FAC_ADD_PTR'
      FieldName = 'SUPP_FAC_ADD_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 5
    end
    object ppDB70ppField7: TppField
      Alignment = taRightJustify
      FieldAlias = 'WAREHOUSE_POINTER'
      FieldName = 'WAREHOUSE_POINTER'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 6
    end
    object ppDB70ppField8: TppField
      Alignment = taRightJustify
      FieldAlias = 'EDIT_BY_EMPL_PTR'
      FieldName = 'EDIT_BY_EMPL_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 7
    end
    object ppDB70ppField9: TppField
      Alignment = taRightJustify
      FieldAlias = 'STATUS'
      FieldName = 'STATUS'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 10
      Position = 8
    end
    object ppDB70ppField10: TppField
      Alignment = taRightJustify
      FieldAlias = 'EXCHANGE_RATE'
      FieldName = 'EXCHANGE_RATE'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 9
    end
    object ppDB70ppField11: TppField
      Alignment = taRightJustify
      FieldAlias = 'SHIPPING_COST'
      FieldName = 'SHIPPING_COST'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 10
    end
    object ppDB70ppField12: TppField
      Alignment = taRightJustify
      FieldAlias = 'FEDERAL_TAX'
      FieldName = 'FEDERAL_TAX'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 11
    end
    object ppDB70ppField13: TppField
      Alignment = taRightJustify
      FieldAlias = 'STATE_TAX'
      FieldName = 'STATE_TAX'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 12
    end
    object ppDB70ppField14: TppField
      Alignment = taRightJustify
      FieldAlias = 'SUB_TOTAL'
      FieldName = 'SUB_TOTAL'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 13
    end
    object ppDB70ppField15: TppField
      FieldAlias = 'CONFIRMATION_NUMBER'
      FieldName = 'CONFIRMATION_NUMBER'
      FieldLength = 20
      DisplayWidth = 20
      Position = 14
    end
    object ppDB70ppField16: TppField
      FieldAlias = #35013#36816#26041#27861
      FieldName = 'SHIPPING_METHOD'
      FieldLength = 20
      DisplayWidth = 20
      Position = 15
    end
    object ppDB70ppField17: TppField
      FieldAlias = 'PO_DATE'
      FieldName = 'PO_DATE'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 16
    end
    object ppDB70ppField18: TppField
      FieldAlias = 'SUPPIER_CONTACT'
      FieldName = 'SUPPIER_CONTACT'
      FieldLength = 20
      DisplayWidth = 20
      Position = 17
    end
    object ppDB70ppField19: TppField
      FieldAlias = 'CONTACT_PHONE'
      FieldName = 'CONTACT_PHONE'
      FieldLength = 14
      DisplayWidth = 14
      Position = 18
    end
    object ppDB70ppField20: TppField
      Alignment = taRightJustify
      FieldAlias = 'DISCOUNT_AMOUNT'
      FieldName = 'DISCOUNT_AMOUNT'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 19
    end
    object ppDB70ppField21: TppField
      FieldAlias = 'DATE_EDITED'
      FieldName = 'DATE_EDITED'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 20
    end
    object ppDB70ppField22: TppField
      FieldAlias = 'PO_TYPE'
      FieldName = 'PO_TYPE'
      FieldLength = 1
      DisplayWidth = 1
      Position = 21
    end
    object ppDB70ppField23: TppField
      FieldAlias = #35831#36141#21333#21495
      FieldName = 'FOB'
      FieldLength = 15
      DisplayWidth = 15
      Position = 22
    end
    object ppDB70ppField24: TppField
      Alignment = taRightJustify
      FieldAlias = 'MISC_CHARGE'
      FieldName = 'MISC_CHARGE'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 23
    end
    object ppDB70ppField25: TppField
      FieldAlias = 'PRINT_DATE'
      FieldName = 'PRINT_DATE'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 24
    end
    object ppDB70ppField26: TppField
      FieldAlias = 'PRINT_TIME'
      FieldName = 'PRINT_TIME'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 25
    end
    object ppDB70ppField27: TppField
      Alignment = taRightJustify
      FieldAlias = 'MULTIPLE_FACTOR'
      FieldName = 'MULTIPLE_FACTOR'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 26
    end
    object ppDB70ppField28: TppField
      Alignment = taRightJustify
      FieldAlias = 'CITY_AMOUNT'
      FieldName = 'CITY_AMOUNT'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 27
    end
    object ppDB70ppField29: TppField
      Alignment = taRightJustify
      FieldAlias = 'COUNTY_AMOUNT'
      FieldName = 'COUNTY_AMOUNT'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 28
    end
    object ppDB70ppField30: TppField
      FieldAlias = 'COLLECT_PREPAID'
      FieldName = 'COLLECT_PREPAID'
      FieldLength = 1
      DisplayWidth = 1
      Position = 29
    end
    object ppDB70ppField31: TppField
      FieldAlias = 'STATE_SHIP_TAX_FLAG'
      FieldName = 'STATE_SHIP_TAX_FLAG'
      FieldLength = 1
      DisplayWidth = 1
      Position = 30
    end
    object ppDB70ppField32: TppField
      FieldAlias = 'STATE_MISC_TAX_FLAG'
      FieldName = 'STATE_MISC_TAX_FLAG'
      FieldLength = 1
      DisplayWidth = 1
      Position = 31
    end
    object ppDB70ppField33: TppField
      FieldAlias = 'STATE_INVT_TAX_FLAG'
      FieldName = 'STATE_INVT_TAX_FLAG'
      FieldLength = 1
      DisplayWidth = 1
      Position = 32
    end
    object ppDB70ppField34: TppField
      Alignment = taRightJustify
      FieldAlias = 'CURRENCY_PTR'
      FieldName = 'CURRENCY_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 33
    end
    object ppDB70ppField35: TppField
      Alignment = taRightJustify
      FieldAlias = 'SECOND_WHSE_PTR'
      FieldName = 'SECOND_WHSE_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 34
    end
    object ppDB70ppField36: TppField
      FieldAlias = 'PO_REV_NO'
      FieldName = 'PO_REV_NO'
      FieldLength = 5
      DisplayWidth = 5
      Position = 35
    end
    object ppDB70ppField37: TppField
      Alignment = taRightJustify
      FieldAlias = 'PAYMENT_TERMS'
      FieldName = 'PAYMENT_TERMS'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 36
    end
    object ppDB70ppField38: TppField
      Alignment = taRightJustify
      FieldAlias = 'CASH_DISCOUNT'
      FieldName = 'CASH_DISCOUNT'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 37
    end
    object ppDB70ppField39: TppField
      Alignment = taRightJustify
      FieldAlias = 'DISCOUNT_DAYS'
      FieldName = 'DISCOUNT_DAYS'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 38
    end
    object ppDB70ppField40: TppField
      Alignment = taRightJustify
      FieldAlias = 'CASH_DISCOUNT2'
      FieldName = 'CASH_DISCOUNT2'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 39
    end
    object ppDB70ppField41: TppField
      Alignment = taRightJustify
      FieldAlias = 'DISCOUNT2_DAYS'
      FieldName = 'DISCOUNT2_DAYS'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 40
    end
    object ppDB70ppField42: TppField
      Alignment = taRightJustify
      FieldAlias = 'PURCHASE_ORDER_TYPE'
      FieldName = 'PURCHASE_ORDER_TYPE'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 10
      Position = 41
    end
    object ppDB70ppField43: TppField
      FieldAlias = 'EXPIRED_DATE'
      FieldName = 'EXPIRED_DATE'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 42
    end
    object ppDB70ppField44: TppField
      FieldAlias = 'ANALYSIS_CODE_1'
      FieldName = 'ANALYSIS_CODE_1'
      FieldLength = 20
      DisplayWidth = 20
      Position = 43
    end
    object ppDB70ppField45: TppField
      FieldAlias = 'ANALYSIS_CODE_2'
      FieldName = 'ANALYSIS_CODE_2'
      FieldLength = 20
      DisplayWidth = 20
      Position = 44
    end
    object ppDB70ppField46: TppField
      FieldAlias = 'ANALYSIS_CODE_3'
      FieldName = 'ANALYSIS_CODE_3'
      FieldLength = 20
      DisplayWidth = 20
      Position = 45
    end
    object ppDB70ppField47: TppField
      FieldAlias = 'ANALYSIS_CODE_4'
      FieldName = 'ANALYSIS_CODE_4'
      FieldLength = 20
      DisplayWidth = 20
      Position = 46
    end
    object ppDB70ppField48: TppField
      FieldAlias = #20184#27454#26041#27861
      FieldName = 'ANALYSIS_CODE_5'
      FieldLength = 20
      DisplayWidth = 20
      Position = 47
    end
    object ppDB70ppField49: TppField
      FieldAlias = #36135#24065#20195#30721
      FieldName = 'curr_code'
      FieldLength = 5
      DisplayWidth = 5
      Position = 48
    end
    object ppDB70ppField50: TppField
      FieldAlias = #36135#24065#21517#31216
      FieldName = 'curr_name'
      FieldLength = 20
      DisplayWidth = 20
      Position = 49
    end
    object ppDB70ppField51: TppField
      FieldAlias = #35013#36816#22320#22336
      FieldName = 'factory_location'
      FieldLength = 20
      DisplayWidth = 20
      Position = 50
    end
    object ppDB70ppField52: TppField
      Alignment = taRightJustify
      FieldAlias = 'shipping_lead_time'
      FieldName = 'shipping_lead_time'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 51
    end
  end
  object DataSource1: TDataSource
    DataSet = DM.ADO107011
    Left = 97
    Top = 171
  end
  object ppDB7011: TppDBPipeline
    DataSource = DataSource1
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB7011'
    Left = 128
    Top = 171
  end
  object ppReport1: TppReport
    AutoStop = False
    DataPipeline = ppDB72
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = #26434#39033#37319#36141#35746#21333
    PrinterSetup.Orientation = poLandscape
    PrinterSetup.PaperName = 'A4 210 x 297 '#27627#31859
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 210000
    PrinterSetup.mmPaperWidth = 297000
    PrinterSetup.PaperSize = 9
    SaveAsTemplate = True
    Template.FileName = 'R:\NIERP\Report\misc_purchorder.rtm'
    Units = utMillimeters
    BeforePrint = ppReport1BeforePrint
    DeviceType = 'Screen'
    OnPreviewFormCreate = ppReport1PreviewFormCreate
    OutlineSettings.CreateNode = True
    OutlineSettings.CreatePageNodes = True
    OutlineSettings.Enabled = False
    OutlineSettings.Visible = False
    PreviewFormSettings.WindowState = wsMaximized
    PreviewFormSettings.ZoomSetting = zs100Percent
    TextSearchSettings.DefaultString = '<FindText>'
    TextSearchSettings.Enabled = False
    Left = 165
    Top = 139
    Version = '7.01'
    mmColumnWidth = 0
    DataPipelineName = 'ppDB72'
    object ppTitleBand1: TppTitleBand
      mmBottomOffset = 0
      mmHeight = 53446
      mmPrintPosition = 0
      object ppDBText1: TppDBText
        UserName = 'DBText1'
        AutoSize = True
        DataField = 'warehouse_name'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 14
        Font.Style = [fsBold]
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 5969
        mmLeft = 38100
        mmTop = 3440
        mmWidth = 33655
        BandType = 1
      end
      object ppDBImage1: TppDBImage
        UserName = 'DBImage1'
        MaintainAspectRatio = False
        Stretch = True
        DataField = 'Company_Icon'
        DataPipeline = ppDB493
        GraphicType = 'Bitmap'
        ParentDataPipeline = False
        DataPipelineName = 'ppDB493'
        mmHeight = 19050
        mmLeft = 6085
        mmTop = 3175
        mmWidth = 19050
        BandType = 1
      end
      object ppLabel1: TppLabel
        UserName = 'Label1'
        Caption = #20379#24212#21830':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3493
        mmLeft = 10848
        mmTop = 25665
        mmWidth = 9737
        BandType = 1
      end
      object ppLabel2: TppLabel
        UserName = 'Label2'
        Caption = #32852#32476#20154':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 10848
        mmTop = 30692
        mmWidth = 9790
        BandType = 1
      end
      object ppLabel3: TppLabel
        UserName = 'Label3'
        Caption = #35013#36816#22320#28857':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 7938
        mmTop = 34925
        mmWidth = 12700
        BandType = 1
      end
      object ppLabel4: TppLabel
        UserName = 'Label4'
        Caption = #22320#22336':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 13758
        mmTop = 39688
        mmWidth = 6879
        BandType = 1
      end
      object ppLabel8: TppLabel
        UserName = 'Label8'
        Caption = #20132#36135#22320#28857':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 136525
        mmTop = 39688
        mmWidth = 11906
        BandType = 1
      end
      object ppLabel9: TppLabel
        UserName = 'Label9'
        Caption = #30005#35805':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 81492
        mmTop = 30692
        mmWidth = 6879
        BandType = 1
      end
      object ppLabel10: TppLabel
        UserName = 'Label10'
        Caption = #35013#36816#26041#27861':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 135732
        mmTop = 44450
        mmWidth = 12700
        BandType = 1
      end
      object ppLabel11: TppLabel
        UserName = 'Label11'
        Caption = #32852#32476#20154':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 78581
        mmTop = 39688
        mmWidth = 9790
        BandType = 1
      end
      object ppLabel12: TppLabel
        UserName = 'Label12'
        Caption = #30005#35805'/'#20256#30495':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 75671
        mmTop = 44450
        mmWidth = 12700
        BandType = 1
      end
      object ppLabel18: TppLabel
        UserName = 'Label18'
        Caption = #35746#21333#32534#21495':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 184150
        mmTop = 29898
        mmWidth = 12700
        BandType = 1
      end
      object ppLabel19: TppLabel
        UserName = 'Label19'
        Caption = #35746#21333#26085#26399':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 136261
        mmTop = 30692
        mmWidth = 11938
        BandType = 1
      end
      object ppLabel17: TppLabel
        UserName = 'Label17'
        Caption = #36135#24065':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 190236
        mmTop = 39688
        mmWidth = 6879
        BandType = 1
      end
      object ppDBText2: TppDBText
        UserName = 'DBText2'
        AutoSize = True
        DataField = 'code'
        DataPipeline = ppDB0070
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB0070'
        mmHeight = 3598
        mmLeft = 23283
        mmTop = 25665
        mmWidth = 8043
        BandType = 1
      end
      object ppDBText3: TppDBText
        UserName = 'DBText3'
        AutoSize = True
        DataField = 'supplier_name'
        DataPipeline = ppDB0070
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB0070'
        mmHeight = 3598
        mmLeft = 34396
        mmTop = 25665
        mmWidth = 42968
        BandType = 1
      end
      object ppDBText4: TppDBText
        UserName = 'DBText4'
        AutoSize = True
        DataField = 'SUPPIER_CONTACT'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3598
        mmLeft = 23283
        mmTop = 30692
        mmWidth = 27728
        BandType = 1
      end
      object ppDBText5: TppDBText
        UserName = 'DBText5'
        AutoSize = True
        DataField = 'factory_location'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3598
        mmLeft = 23283
        mmTop = 34925
        mmWidth = 20108
        BandType = 1
      end
      object ppDBText6: TppDBText
        UserName = 'DBText6'
        AutoSize = True
        DataField = 'CONTACT_PHONE'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3598
        mmLeft = 90488
        mmTop = 30427
        mmWidth = 25188
        BandType = 1
      end
      object ppDBText7: TppDBText
        UserName = 'DBText7'
        AutoSize = True
        DataField = 'SHIPPING_METHOD'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3704
        mmLeft = 150548
        mmTop = 44450
        mmWidth = 27517
        BandType = 1
      end
      object ppLabel5: TppLabel
        UserName = 'Label5'
        Caption = 'Label5'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 23283
        mmTop = 39688
        mmWidth = 8467
        BandType = 1
      end
      object ppLabel6: TppLabel
        UserName = 'Label6'
        Caption = 'Label6'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 23283
        mmTop = 44450
        mmWidth = 8467
        BandType = 1
      end
      object ppLabel7: TppLabel
        UserName = 'Label7'
        Caption = 'Label7'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 23283
        mmTop = 49213
        mmWidth = 8467
        BandType = 1
      end
      object ppLabel14: TppLabel
        UserName = 'Label14'
        Caption = 'Label14'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 90488
        mmTop = 39688
        mmWidth = 10054
        BandType = 1
      end
      object ppLabel15: TppLabel
        UserName = 'Label15'
        Caption = 'Label15'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 90488
        mmTop = 44450
        mmWidth = 10054
        BandType = 1
      end
      object ppLabel16: TppLabel
        UserName = 'Label16'
        Caption = 'Label16'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 110596
        mmTop = 44450
        mmWidth = 10054
        BandType = 1
      end
      object ppDBText8: TppDBText
        UserName = 'DBText8'
        AutoSize = True
        DataField = 'ADDRESS_LINE_3'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 3175
        mmLeft = 150548
        mmTop = 39688
        mmWidth = 21960
        BandType = 1
      end
      object ppDBText9: TppDBText
        UserName = 'DBText9'
        AutoSize = True
        DataField = 'PO_NUMBER'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3704
        mmLeft = 198967
        mmTop = 29898
        mmWidth = 17992
        BandType = 1
      end
      object ppDBText10: TppDBText
        UserName = 'DBText10'
        AutoSize = True
        DataField = 'PO_DATE'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3387
        mmLeft = 150284
        mmTop = 30692
        mmWidth = 13123
        BandType = 1
      end
      object ppDBText11: TppDBText
        UserName = 'DBText11'
        AutoSize = True
        DataField = 'curr_name'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3704
        mmLeft = 199232
        mmTop = 39688
        mmWidth = 13758
        BandType = 1
      end
      object ppDBText26: TppDBText
        UserName = 'DBText26'
        AutoSize = True
        DataField = 'FOB'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3704
        mmLeft = 242888
        mmTop = 39688
        mmWidth = 5821
        BandType = 1
      end
      object ppLabel41: TppLabel
        UserName = 'Label41'
        Caption = #35831#36141#32534#21495':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 228071
        mmTop = 39688
        mmWidth = 12700
        BandType = 1
      end
      object ppDBText22: TppDBText
        UserName = 'DBText22'
        AutoSize = True
        DataField = 'address_line_2'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 4191
        mmLeft = 38365
        mmTop = 10054
        mmWidth = 24130
        BandType = 1
      end
      object ppLabel26: TppLabel
        UserName = 'Label26'
        Caption = #22320#22336':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 38365
        mmTop = 15346
        mmWidth = 8202
        BandType = 1
      end
      object ppDBText30: TppDBText
        UserName = 'DBText30'
        AutoSize = True
        DataField = 'address_line_1'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 4191
        mmLeft = 48154
        mmTop = 15346
        mmWidth = 24130
        BandType = 1
      end
      object ppLabel29: TppLabel
        UserName = 'Label29'
        Caption = #30005#35805':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 38365
        mmTop = 20108
        mmWidth = 7938
        BandType = 1
      end
      object ppDBText31: TppDBText
        UserName = 'DBText31'
        AutoSize = True
        DataField = 'phone'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 4233
        mmLeft = 48154
        mmTop = 20108
        mmWidth = 8202
        BandType = 1
      end
      object ppLabel30: TppLabel
        UserName = 'Label30'
        Caption = #20256#30495':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 80433
        mmTop = 20373
        mmWidth = 7938
        BandType = 1
      end
      object ppDBText32: TppDBText
        UserName = 'DBText32'
        AutoSize = True
        DataField = 'fax'
        DataPipeline = ppDB15
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 10
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB15'
        mmHeight = 4233
        mmLeft = 90488
        mmTop = 20373
        mmWidth = 4233
        BandType = 1
      end
      object ppLabel40: TppLabel
        UserName = 'Label40'
        Caption = 'PURCHASING ORDER'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 14
        Font.Style = []
        Transparent = True
        mmHeight = 5715
        mmLeft = 195527
        mmTop = 3704
        mmWidth = 52070
        BandType = 1
      end
      object ppLabel44: TppLabel
        UserName = 'Label44'
        Caption = #37319#36141#35746#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 14
        Font.Style = [fsBold]
        Transparent = True
        mmHeight = 5821
        mmLeft = 209815
        mmTop = 10319
        mmWidth = 20902
        BandType = 1
      end
      object ppLabel45: TppLabel
        UserName = 'Label45'
        Caption = #35746#21333#21046#20316':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 136261
        mmTop = 34925
        mmWidth = 11938
        BandType = 1
      end
      object ppDBText33: TppDBText
        UserName = 'DBText33'
        AutoSize = True
        DataField = 'employee_name'
        DataPipeline = ppDB0070
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB0070'
        mmHeight = 3302
        mmLeft = 150548
        mmTop = 34925
        mmWidth = 16891
        BandType = 1
      end
      object ppLabel39: TppLabel
        UserName = 'Label39'
        Caption = #20184#27454#26465#20214':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 184680
        mmTop = 45508
        mmWidth = 12700
        BandType = 1
      end
      object ppDBText29: TppDBText
        UserName = 'DBText29'
        AutoSize = True
        DataField = 'ANALYSIS_CODE_5'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3302
        mmLeft = 199496
        mmTop = 45508
        mmWidth = 24003
        BandType = 1
      end
      object ppDBText35: TppDBText
        UserName = 'DBText35'
        AutoSize = True
        DataField = 'PO_REV_NO'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3175
        mmLeft = 242888
        mmTop = 44979
        mmWidth = 15081
        BandType = 1
      end
      object ppLabel48: TppLabel
        UserName = 'Label48'
        Caption = #35831#36141#37096#38376':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 228865
        mmTop = 44979
        mmWidth = 11906
        BandType = 1
      end
      object ppLabel49: TppLabel
        UserName = 'Label49'
        Caption = #39029#30721':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 189971
        mmTop = 34925
        mmWidth = 6350
        BandType = 1
      end
      object ppSystemVariable1: TppSystemVariable
        UserName = 'SystemVariable1'
        VarType = vtPageNo
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 204523
        mmTop = 34925
        mmWidth = 1323
        BandType = 1
      end
      object ppSystemVariable2: TppSystemVariable
        UserName = 'SystemVariable2'
        VarType = vtPageCount
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 216430
        mmTop = 34925
        mmWidth = 1323
        BandType = 1
      end
      object ppLabel50: TppLabel
        UserName = 'Label50'
        Caption = #31532
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 199496
        mmTop = 34925
        mmWidth = 2910
        BandType = 1
      end
      object ppLabel51: TppLabel
        UserName = 'Label51'
        Caption = #39029','#20849
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 208227
        mmTop = 34925
        mmWidth = 6350
        BandType = 1
      end
      object ppLabel52: TppLabel
        UserName = 'Label52'
        Caption = #39029
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 220928
        mmTop = 34925
        mmWidth = 2910
        BandType = 1
      end
      object ppLabel53: TppLabel
        UserName = 'Label53'
        Caption = #31080#25454#31181#31867':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3175
        mmLeft = 228865
        mmTop = 34925
        mmWidth = 11906
        BandType = 1
      end
      object ppDBText36: TppDBText
        UserName = 'DBText36'
        AutoSize = True
        DataField = 'ANALYSIS_CODE_4'
        DataPipeline = ppDB70
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3175
        mmLeft = 242888
        mmTop = 34660
        mmWidth = 24077
        BandType = 1
      end
    end
    object ppHeaderBand1: TppHeaderBand
      mmBottomOffset = 0
      mmHeight = 5292
      mmPrintPosition = 0
      object ppShape1: TppShape
        UserName = 'Shape1'
        mmHeight = 5292
        mmLeft = 12965
        mmTop = 0
        mmWidth = 256382
        BandType = 0
      end
      object ppLabel20: TppLabel
        UserName = 'Label20'
        Caption = #26434#39033#25551#36848
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 30427
        mmTop = 1058
        mmWidth = 11906
        BandType = 0
      end
      object ppLabel21: TppLabel
        UserName = 'Label21'
        Caption = #21040#36135#26085#26399
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 125413
        mmTop = 794
        mmWidth = 11906
        BandType = 0
      end
      object ppLabel22: TppLabel
        UserName = 'Label22'
        Caption = #25968#37327
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 168011
        mmTop = 794
        mmWidth = 5821
        BandType = 0
      end
      object ppLabel23: TppLabel
        UserName = 'Label23'
        Caption = #21547#31246#20215
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 189707
        mmTop = 529
        mmWidth = 10054
        BandType = 0
      end
      object ppLabel24: TppLabel
        UserName = 'Label24'
        Caption = #19981#21547#31246#37329#39069
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 794
        mmWidth = 16933
        BandType = 0
      end
      object ppLabel25: TppLabel
        UserName = 'Label25'
        Caption = #31246#37329
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 260086
        mmTop = 794
        mmWidth = 5821
        BandType = 0
      end
      object ppLine12: TppLine
        UserName = 'Line11'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 71173
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine13: TppLine
        UserName = 'Line13'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 157957
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine14: TppLine
        UserName = 'Line14'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 182034
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine15: TppLine
        UserName = 'Line15'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 205846
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine16: TppLine
        UserName = 'Line16'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 231246
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine24: TppLine
        UserName = 'Line24'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 140759
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLine25: TppLine
        UserName = 'Line25'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 247121
        mmTop = 0
        mmWidth = 265
        BandType = 0
      end
      object ppLabel42: TppLabel
        UserName = 'Label42'
        Caption = #21333#20301
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3440
        mmLeft = 146050
        mmTop = 1058
        mmWidth = 6879
        BandType = 0
      end
      object ppLabel43: TppLabel
        UserName = 'Label43'
        Caption = #31246#29575'%'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3387
        mmLeft = 236803
        mmTop = 794
        mmWidth = 9313
        BandType = 0
      end
      object ppLabel13: TppLabel
        UserName = 'Label13'
        Caption = #39033#30446
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 16933
        mmTop = 529
        mmWidth = 5588
        BandType = 0
      end
      object ppLine1: TppLine
        UserName = 'Line1'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 26194
        mmTop = 265
        mmWidth = 265
        BandType = 0
      end
      object ppLine2: TppLine
        UserName = 'Line2'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5027
        mmLeft = 121444
        mmTop = 265
        mmWidth = 265
        BandType = 0
      end
      object ppLabel46: TppLabel
        UserName = 'Label46'
        Caption = #35268#26684
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 92340
        mmTop = 1058
        mmWidth = 5588
        BandType = 0
      end
    end
    object ppDetailBand1: TppDetailBand
      mmBottomOffset = 0
      mmHeight = 5292
      mmPrintPosition = 0
      object ppDBText12: TppDBText
        UserName = 'DBText12'
        AutoSize = True
        DataField = 'DESCRIPTION'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3302
        mmLeft = 28310
        mmTop = 794
        mmWidth = 4699
        BandType = 4
      end
      object ppDBText13: TppDBText
        UserName = 'DBText13'
        DataField = 'DEL_DATE'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 122767
        mmTop = 794
        mmWidth = 17198
        BandType = 4
      end
      object ppDBText14: TppDBText
        UserName = 'DBText14'
        DataField = 'QUAN_ORD'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 160867
        mmTop = 1058
        mmWidth = 17198
        BandType = 4
      end
      object ppDBText15: TppDBText
        UserName = 'DBText15'
        DataField = 'UNIT_PRICE'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 186002
        mmTop = 794
        mmWidth = 17198
        BandType = 4
      end
      object ppDBText16: TppDBText
        UserName = 'DBText16'
        DataField = 'sim_total'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 794
        mmWidth = 17198
        BandType = 4
      end
      object ppDBText17: TppDBText
        UserName = 'DBText17'
        DataField = 'tax_total'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 250561
        mmTop = 1058
        mmWidth = 17198
        BandType = 4
      end
      object ppLine4: TppLine
        UserName = 'Line4'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 12965
        mmTop = 5027
        mmWidth = 256117
        BandType = 4
      end
      object ppLine5: TppLine
        UserName = 'Line5'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 12965
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine6: TppLine
        UserName = 'Line6'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 71173
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine7: TppLine
        UserName = 'Line7'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 157957
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine8: TppLine
        UserName = 'Line8'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 182034
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine9: TppLine
        UserName = 'Line9'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 205846
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine10: TppLine
        UserName = 'Line10'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 231246
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine11: TppLine
        UserName = 'Line101'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 269082
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppDBCalc1: TppDBCalc
        UserName = 'DBCalc1'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DBCalcType = dcCount
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 14288
        mmTop = 794
        mmWidth = 10054
        BandType = 4
      end
      object ppLine23: TppLine
        UserName = 'Line23'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 140759
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine26: TppLine
        UserName = 'Line102'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 247121
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppDBText27: TppDBText
        UserName = 'DBText27'
        DataField = 'unit_name'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 142875
        mmTop = 794
        mmWidth = 12965
        BandType = 4
      end
      object ppDBText28: TppDBText
        UserName = 'DBText28'
        DataField = 'STATE_TAX'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3387
        mmLeft = 233892
        mmTop = 1058
        mmWidth = 12435
        BandType = 4
      end
      object ppLine3: TppLine
        UserName = 'Line3'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 121444
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppLine28: TppLine
        UserName = 'Line28'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 5292
        mmLeft = 26194
        mmTop = 0
        mmWidth = 265
        BandType = 4
      end
      object ppDBText34: TppDBText
        UserName = 'DBText34'
        DataField = 'GUI_GE'
        DataPipeline = ppDB72
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3302
        mmLeft = 75406
        mmTop = 794
        mmWidth = 17198
        BandType = 4
      end
    end
    object ppFooterBand1: TppFooterBand
      mmBottomOffset = 0
      mmHeight = 64029
      mmPrintPosition = 0
      object ppLabel27: TppLabel
        UserName = 'Label27'
        Caption = #22791#27880':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = [fsItalic]
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 3440
        mmLeft = 48154
        mmTop = 10054
        mmWidth = 7673
        BandType = 8
      end
      object ppDBText18: TppDBText
        UserName = 'DBText18'
        AutoSize = True
        DataField = 'NOTE_PAD_LINE_1'
        DataPipeline = ppDB7011
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB7011'
        mmHeight = 3440
        mmLeft = 57150
        mmTop = 13758
        mmWidth = 17727
        BandType = 8
      end
      object ppDBText19: TppDBText
        UserName = 'DBText19'
        AutoSize = True
        DataField = 'NOTE_PAD_LINE_2'
        DataPipeline = ppDB7011
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB7011'
        mmHeight = 3440
        mmLeft = 57150
        mmTop = 17727
        mmWidth = 32544
        BandType = 8
      end
      object ppDBText20: TppDBText
        UserName = 'DBText20'
        AutoSize = True
        DataField = 'NOTE_PAD_LINE_3'
        DataPipeline = ppDB7011
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB7011'
        mmHeight = 3440
        mmLeft = 57150
        mmTop = 21696
        mmWidth = 17198
        BandType = 8
      end
      object ppDBText21: TppDBText
        UserName = 'DBText21'
        AutoSize = True
        DataField = 'NOTE_PAD_LINE_4'
        DataPipeline = ppDB7011
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        Transparent = True
        DataPipelineName = 'ppDB7011'
        mmHeight = 3440
        mmLeft = 57150
        mmTop = 25665
        mmWidth = 17198
        BandType = 8
      end
      object ppLabel28: TppLabel
        UserName = 'Label28'
        Caption = #35201#27880#20107#39033':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 3440
        mmLeft = 47890
        mmTop = 34660
        mmWidth = 14288
        BandType = 8
      end
      object ppMemo1: TppMemo
        UserName = 'Memo1'
        Caption = 'Memo1'
        CharWrap = False
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Lines.Strings = (
          '1'#65294#26412#20844#21496#20005#31105#36159#36162#34892#20026#65292#19968#32463#21457#29616#26412#26412#20844#21496#23558#25298#20184#36135#27454#12290
          '2'#65294#27492#35746#21333#32463#20379#26041#30830#35748#21518#65292#24517#39035#20005#23432#20132#36135#26399#65292#22914#26377#29305#29305#27530#24773#20917#26080#27861#25353#26102#20132#36135#65292#24517#39035#20110#20132#26399#21069#20004#26085#32852#32476#26412#20844#21496#37319#36141#37096#20197#21327#21830#12290
          '3'#65294#35831#30830#20445#20135#21697#21697#36136#65292#33509#21457#29983#21697#36136#19981#33391#29616#35937#65292#24517#39035#20110#19968#20010#24037#20316#26085#20869#26356#25442#19981#33391#21697#65292#21542#21017#19968#20999#21518#26524#30001#20379#26041#25215#25285#12290
          '4'#65294#20110#36865#36135#21333#19978#24517#39035#27880#26126#26412#20844#21496#29289#21697#21517#31216#65292#25968#37327#65292#21333#20215#65292#24635#20215#20197#21450'PO'#21333#21495#12290
          '5'#65294#19968#24352#36865#36135#21333#21482#38480#24320#19968#24352'PO'#20043#29289#26009#12290
          '6'#65294#22914#36865#36135#21333#20013#26377#20551#36135#65292#26412#20844#21496#26377#26435#27809#25910#20551#36135#24182#25298#20184#26412#21333#36135#27454#12290)
        Transparent = True
        mmHeight = 19050
        mmLeft = 56886
        mmTop = 38100
        mmWidth = 153459
        BandType = 8
        mmBottomOffset = 0
        mmOverFlowOffset = 0
        mmStopPosition = 0
        mmLeading = 0
      end
      object ppLabel47: TppLabel
        UserName = 'Label47'
        AutoSize = False
        Caption = 
          #27880#26126#65306#20026#20102#30830#20445#21508#20379#24212#21830#30340#21033#30410#65292#22914#26377#26412#20844#21496#32844#21592#21521' '#21496#32034#21462#20219#20309#21033#30410#65292#35831#30452#25320#20030#25253#28909#32447#65306' 13602252358'#21608#29983#65292'136003399' +
          '67'#25140#29983#27965#12290'('#25910#21040#27492#21333#21518#65292#35831#20110#19968#20010#24037#20316#26085#20869#21153#24517#31614#22238') '
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3302
        mmLeft = 28840
        mmTop = 58738
        mmWidth = 221192
        BandType = 8
      end
      object ppLine29: TppLine
        UserName = 'Line21'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 12965
        mmTop = 62706
        mmWidth = 256382
        BandType = 8
      end
    end
    object ppSummaryBand1: TppSummaryBand
      mmBottomOffset = 0
      mmHeight = 25929
      mmPrintPosition = 0
      object ppLabel37: TppLabel
        UserName = 'Label37'
        Caption = #22823#20889':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3493
        mmLeft = 39688
        mmTop = 21431
        mmWidth = 6773
        BandType = 7
      end
      object ppLabel31: TppLabel
        UserName = 'Label31'
        Caption = #23567#35745':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3493
        mmLeft = 198173
        mmTop = 794
        mmWidth = 6773
        BandType = 7
      end
      object ppLabel32: TppLabel
        UserName = 'Label32'
        Caption = #26434#39033#36153#29992':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3493
        mmLeft = 192617
        mmTop = 5821
        mmWidth = 12700
        BandType = 7
      end
      object ppLabel33: TppLabel
        UserName = 'Label33'
        Caption = #36816#36755#36153#29992':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3493
        mmLeft = 192617
        mmTop = 11113
        mmWidth = 12700
        BandType = 7
      end
      object ppLabel34: TppLabel
        UserName = 'Label34'
        Caption = #26434#39033#36816#36755#31246':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3493
        mmLeft = 189707
        mmTop = 15610
        mmWidth = 15663
        BandType = 7
      end
      object ppLabel35: TppLabel
        UserName = 'Label35'
        Caption = #24635#35745':'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3440
        mmLeft = 198173
        mmTop = 21696
        mmWidth = 6879
        BandType = 7
      end
      object ppLine17: TppLine
        UserName = 'Line12'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 12965
        mmTop = 4763
        mmWidth = 256382
        BandType = 7
      end
      object ppLine18: TppLine
        UserName = 'Line17'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 25929
        mmLeft = 12965
        mmTop = 0
        mmWidth = 265
        BandType = 7
      end
      object ppLine19: TppLine
        UserName = 'Line19'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 12965
        mmTop = 25664
        mmWidth = 256382
        BandType = 7
      end
      object ppLine20: TppLine
        UserName = 'Line20'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 25929
        mmLeft = 269082
        mmTop = 0
        mmWidth = 265
        BandType = 7
      end
      object ppLine21: TppLine
        UserName = 'Line18'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 4763
        mmLeft = 206905
        mmTop = 0
        mmWidth = 265
        BandType = 7
      end
      object ppLine22: TppLine
        UserName = 'Line22'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 4763
        mmLeft = 231246
        mmTop = 0
        mmWidth = 265
        BandType = 7
      end
      object ppDBCalc2: TppDBCalc
        UserName = 'DBCalc2'
        DataField = 'sim_total'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 794
        mmWidth = 17198
        BandType = 7
      end
      object ppDBCalc3: TppDBCalc
        UserName = 'DBCalc3'
        DataField = 'tax_total'
        DataPipeline = ppDB72
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB72'
        mmHeight = 3493
        mmLeft = 251090
        mmTop = 794
        mmWidth = 17198
        BandType = 7
      end
      object ppDBText23: TppDBText
        UserName = 'DBText23'
        DataField = 'MISC_CHARGE'
        DataPipeline = ppDB70
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 6085
        mmWidth = 17198
        BandType = 7
      end
      object ppDBText24: TppDBText
        UserName = 'DBText24'
        DataField = 'SHIPPING_COST'
        DataPipeline = ppDB70
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 11377
        mmWidth = 17198
        BandType = 7
      end
      object ppLabel36: TppLabel
        UserName = 'Label36'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 3440
        mmLeft = 218282
        mmTop = 15610
        mmWidth = 10054
        BandType = 7
      end
      object ppDBText25: TppDBText
        UserName = 'DBText25'
        DataField = 'SUB_TOTAL'
        DataPipeline = ppDB70
        DisplayFormat = '#,0.00;-#,0.00'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        ParentDataPipeline = False
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB70'
        mmHeight = 3440
        mmLeft = 211138
        mmTop = 21696
        mmWidth = 17198
        BandType = 7
      end
      object ppLabel38: TppLabel
        UserName = 'Label38'
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = #23435#20307
        Font.Size = 8
        Font.Style = []
        Transparent = True
        mmHeight = 3493
        mmLeft = 48419
        mmTop = 21431
        mmWidth = 10160
        BandType = 7
      end
      object ppLine27: TppLine
        UserName = 'Line27'
        Position = lpLeft
        Weight = 0.75
        mmHeight = 4763
        mmLeft = 247121
        mmTop = 0
        mmWidth = 265
        BandType = 7
      end
      object ppLine30: TppLine
        UserName = 'Line30'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 12965
        mmTop = 19579
        mmWidth = 256382
        BandType = 7
      end
    end
  end
  object ppDB72: TppDBPipeline
    DataSource = DM.DataSource4
    UserName = 'DB72'
    Left = 128
    Top = 140
    object ppDB72ppField1: TppField
      Alignment = taRightJustify
      FieldAlias = 'RKEY'
      FieldName = 'RKEY'
      FieldLength = 0
      DataType = dtLongint
      DisplayWidth = 0
      Position = 0
    end
    object ppDB72ppField2: TppField
      Alignment = taRightJustify
      FieldAlias = 'POPTR'
      FieldName = 'POPTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 1
    end
    object ppDB72ppField3: TppField
      FieldAlias = 'DESCRIPTION'
      FieldName = 'DESCRIPTION'
      FieldLength = 40
      DisplayWidth = 40
      Position = 2
    end
    object ppDB72ppField4: TppField
      FieldAlias = 'GUI_GE'
      FieldName = 'GUI_GE'
      FieldLength = 50
      DisplayWidth = 50
      Position = 3
    end
    object ppDB72ppField5: TppField
      Alignment = taRightJustify
      FieldAlias = 'QUAN_ORD'
      FieldName = 'QUAN_ORD'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 4
    end
    object ppDB72ppField6: TppField
      Alignment = taRightJustify
      FieldAlias = 'QUAN_INVD'
      FieldName = 'QUAN_INVD'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 5
    end
    object ppDB72ppField7: TppField
      Alignment = taRightJustify
      FieldAlias = 'UNIT_PRICE'
      FieldName = 'UNIT_PRICE'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 6
    end
    object ppDB72ppField8: TppField
      Alignment = taRightJustify
      FieldAlias = 'STATE_TAX'
      FieldName = 'STATE_TAX'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 7
    end
    object ppDB72ppField9: TppField
      Alignment = taRightJustify
      FieldAlias = 'GL_PTR'
      FieldName = 'GL_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 8
    end
    object ppDB72ppField10: TppField
      Alignment = taRightJustify
      FieldAlias = 'QUANTITY_RECEIVED'
      FieldName = 'QUANTITY_RECEIVED'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 9
    end
    object ppDB72ppField11: TppField
      FieldAlias = 'DESCRIPTION2'
      FieldName = 'DESCRIPTION2'
      FieldLength = 40
      DisplayWidth = 40
      Position = 10
    end
    object ppDB72ppField12: TppField
      FieldAlias = 'DEL_DATE'
      FieldName = 'DEL_DATE'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 11
    end
    object ppDB72ppField13: TppField
      Alignment = taRightJustify
      FieldAlias = 'UNIT_PTR'
      FieldName = 'UNIT_PTR'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 12
    end
    object ppDB72ppField14: TppField
      FieldAlias = 'PRINTED_DATE'
      FieldName = 'PRINTED_DATE'
      FieldLength = 0
      DataType = dtDateTime
      DisplayWidth = 18
      Position = 13
    end
    object ppDB72ppField15: TppField
      Alignment = taRightJustify
      FieldAlias = 'sim_total'
      FieldName = 'sim_total'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 14
    end
    object ppDB72ppField16: TppField
      Alignment = taRightJustify
      FieldAlias = 'tax_total'
      FieldName = 'tax_total'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 10
      Position = 15
    end
    object ppDB72ppField17: TppField
      FieldAlias = 'unit_name'
      FieldName = 'unit_name'
      FieldLength = 20
      DisplayWidth = 20
      Position = 16
    end
  end
  object DataSource3: TDataSource
    DataSet = DM.AQ0015
    Left = 96
    Top = 283
  end
  object ppDB15: TppDBPipeline
    DataSource = DataSource3
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB15'
    Left = 128
    Top = 283
    object ppDB15ppField1: TppField
      Alignment = taRightJustify
      FieldAlias = 'RKEY'
      FieldName = 'RKEY'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 0
      Position = 0
    end
    object ppDB15ppField2: TppField
      FieldAlias = 'WAREHOUSE_CODE'
      FieldName = 'WAREHOUSE_CODE'
      FieldLength = 5
      DisplayWidth = 5
      Position = 1
    end
    object ppDB15ppField3: TppField
      FieldAlias = 'WAREHOUSE_NAME'
      FieldName = 'WAREHOUSE_NAME'
      FieldLength = 70
      DisplayWidth = 70
      Position = 2
    end
    object ppDB15ppField4: TppField
      FieldAlias = 'ENG_NAME'
      FieldName = 'ENG_NAME'
      FieldLength = 70
      DisplayWidth = 70
      Position = 3
    end
    object ppDB15ppField5: TppField
      FieldAlias = 'ABBR_NAME'
      FieldName = 'ABBR_NAME'
      FieldLength = 10
      DisplayWidth = 10
      Position = 4
    end
    object ppDB15ppField6: TppField
      FieldAlias = 'ADDRESS_LINE_1'
      FieldName = 'ADDRESS_LINE_1'
      FieldLength = 70
      DisplayWidth = 70
      Position = 5
    end
    object ppDB15ppField7: TppField
      FieldAlias = 'ADDRESS_LINE_2'
      FieldName = 'ADDRESS_LINE_2'
      FieldLength = 70
      DisplayWidth = 70
      Position = 6
    end
    object ppDB15ppField8: TppField
      FieldAlias = 'ADDRESS_LINE_3'
      FieldName = 'ADDRESS_LINE_3'
      FieldLength = 30
      DisplayWidth = 30
      Position = 7
    end
    object ppDB15ppField9: TppField
      FieldAlias = 'STATE'
      FieldName = 'STATE'
      FieldLength = 10
      DisplayWidth = 10
      Position = 8
    end
    object ppDB15ppField10: TppField
      FieldAlias = 'ZIP'
      FieldName = 'ZIP'
      FieldLength = 10
      DisplayWidth = 10
      Position = 9
    end
    object ppDB15ppField11: TppField
      FieldAlias = 'PHONE'
      FieldName = 'PHONE'
      FieldLength = 14
      DisplayWidth = 14
      Position = 10
    end
    object ppDB15ppField12: TppField
      FieldAlias = 'FAX'
      FieldName = 'FAX'
      FieldLength = 14
      DisplayWidth = 14
      Position = 11
    end
    object ppDB15ppField13: TppField
      FieldAlias = 'TELEX'
      FieldName = 'TELEX'
      FieldLength = 30
      DisplayWidth = 30
      Position = 12
    end
    object ppDB15ppField14: TppField
      FieldAlias = 'WEB'
      FieldName = 'WEB'
      FieldLength = 50
      DisplayWidth = 50
      Position = 13
    end
    object ppDB15ppField15: TppField
      Alignment = taRightJustify
      FieldAlias = 'EMPLOYEE_PTR_1'
      FieldName = 'EMPLOYEE_PTR_1'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 14
    end
    object ppDB15ppField16: TppField
      Alignment = taRightJustify
      FieldAlias = 'EMPLOYEE_PTR_2'
      FieldName = 'EMPLOYEE_PTR_2'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 15
    end
    object ppDB15ppField17: TppField
      Alignment = taRightJustify
      FieldAlias = 'EMPLOYEE_PTR_3'
      FieldName = 'EMPLOYEE_PTR_3'
      FieldLength = 0
      DataType = dtInteger
      DisplayWidth = 10
      Position = 16
    end
    object ppDB15ppField19: TppField
      FieldAlias = 'o_warehouse_name'
      FieldName = 'o_warehouse_name'
      FieldLength = 70
      DisplayWidth = 70
      Position = 17
    end
    object ppDB15ppField20: TppField
      FieldAlias = 'o_eng_name'
      FieldName = 'o_eng_name'
      FieldLength = 70
      DisplayWidth = 70
      Position = 18
    end
    object ppDB15ppField21: TppField
      FieldAlias = 'o_address_1'
      FieldName = 'o_address_1'
      FieldLength = 70
      DisplayWidth = 70
      Position = 19
    end
    object ppDB15ppField22: TppField
      FieldAlias = 'o_address_2'
      FieldName = 'o_address_2'
      FieldLength = 70
      DisplayWidth = 70
      Position = 20
    end
    object ppDB15ppField23: TppField
      FieldAlias = 'o_address_3'
      FieldName = 'o_address_3'
      FieldLength = 50
      DisplayWidth = 50
      Position = 21
    end
    object ppDB15ppField24: TppField
      FieldAlias = 'o_state'
      FieldName = 'o_state'
      FieldLength = 10
      DisplayWidth = 10
      Position = 22
    end
    object ppDB15ppField25: TppField
      FieldAlias = 'o_zip'
      FieldName = 'o_zip'
      FieldLength = 10
      DisplayWidth = 10
      Position = 23
    end
    object ppDB15ppField26: TppField
      FieldAlias = 'o_phone'
      FieldName = 'o_phone'
      FieldLength = 14
      DisplayWidth = 14
      Position = 24
    end
    object ppDB15ppField27: TppField
      FieldAlias = 'o_fax'
      FieldName = 'o_fax'
      FieldLength = 14
      DisplayWidth = 14
      Position = 25
    end
    object ppDB15ppField28: TppField
      FieldAlias = 'o_telex'
      FieldName = 'o_telex'
      FieldLength = 30
      DisplayWidth = 30
      Position = 26
    end
    object ppDB15ppField29: TppField
      FieldAlias = 'o_web'
      FieldName = 'o_web'
      FieldLength = 50
      DisplayWidth = 50
      Position = 27
    end
    object ppDB15ppField30: TppField
      FieldAlias = 'purchase_order'
      FieldName = 'purchase_order'
      FieldLength = 15
      DisplayWidth = 15
      Position = 28
    end
    object ppDB15ppField31: TppField
      FieldAlias = 'o_purchase_order'
      FieldName = 'o_purchase_order'
      FieldLength = 15
      DisplayWidth = 15
      Position = 29
    end
    object ppDB15ppField32: TppField
      FieldAlias = 'picture'
      FieldName = 'picture'
      FieldLength = 0
      DataType = dtBLOB
      DisplayWidth = 10
      Position = 30
      Searchable = False
      Sortable = False
    end
    object ppDB15ppField33: TppField
      FieldAlias = 'o_picture'
      FieldName = 'o_picture'
      FieldLength = 0
      DataType = dtBLOB
      DisplayWidth = 10
      Position = 31
      Searchable = False
      Sortable = False
    end
  end
  object DataSource4: TDataSource
    DataSet = DM.ADO7011
    Left = 97
    Top = 210
  end
  object ppDB11: TppDBPipeline
    DataSource = DataSource4
    OpenDataSource = False
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB11'
    Left = 129
    Top = 210
    object ppDBPipeline1ppField1: TppField
      FieldAlias = 'RKEY'
      FieldName = 'RKEY'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 0
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField2: TppField
      FieldAlias = 'FILE_POINTER'
      FieldName = 'FILE_POINTER'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 1
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField3: TppField
      FieldAlias = 'SOURCE_TYPE'
      FieldName = 'SOURCE_TYPE'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 2
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField4: TppField
      FieldAlias = 'NOTE_PAD_LINE_1'
      FieldName = 'NOTE_PAD_LINE_1'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 3
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField5: TppField
      FieldAlias = 'NOTE_PAD_LINE_2'
      FieldName = 'NOTE_PAD_LINE_2'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 4
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField6: TppField
      FieldAlias = 'NOTE_PAD_LINE_3'
      FieldName = 'NOTE_PAD_LINE_3'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 5
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField7: TppField
      FieldAlias = 'NOTE_PAD_LINE_4'
      FieldName = 'NOTE_PAD_LINE_4'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 6
      Searchable = False
      Sortable = False
    end
    object ppDBPipeline1ppField8: TppField
      FieldAlias = 'memo_text'
      FieldName = 'memo_text'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 7
      Searchable = False
      Sortable = False
    end
  end
end
