object Form_report: TForm_report
  Left = 548
  Top = 285
  Width = 388
  Height = 373
  Caption = #25253#34920
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = '宋体'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 13
  object ADOdata0493: TADOQuery
    Connection = Form1.ADOConnection1
    CursorType = ctStatic
    LockType = ltReadOnly
    Parameters = <>
    SQL.Strings = (
      'select * from data0493')
    Left = 55
    Top = 138
    object ADOdata0493Company_Name: TStringField
      FieldName = 'Company_Name'
      Size = 50
    end
    object ADOdata0493ship_address: TStringField
      FieldName = 'ship_address'
      Size = 50
    end
    object ADOdata0493Company_Icon: TBlobField
      FieldName = 'Company_Icon'
    end
    object ADOdata0493SITE_INFO_ADD_1: TStringField
      FieldName = 'SITE_INFO_ADD_1'
      FixedChar = True
      Size = 50
    end
    object ADOdata0493SITE_INFO_ADD_2: TStringField
      FieldName = 'SITE_INFO_ADD_2'
      FixedChar = True
      Size = 50
    end
    object ADOdata0493SITE_INFO_ADD_3: TStringField
      FieldName = 'SITE_INFO_ADD_3'
      FixedChar = True
      Size = 50
    end
    object ADOdata0493SITE_INFO_PHONE: TStringField
      FieldName = 'SITE_INFO_PHONE'
      FixedChar = True
      Size = 30
    end
  end
  object DataSource1: TDataSource
    DataSet = ADOdata0493
    Left = 86
    Top = 137
  end
  object ppDB493: TppDBPipeline
    DataSource = DataSource1
    RangeEnd = reCurrentRecord
    RangeBegin = rbCurrentRecord
    UserName = 'DB493'
    Left = 118
    Top = 137
    object ppDB493ppField1: TppField
      FieldAlias = 'Company_Name'
      FieldName = 'Company_Name'
      FieldLength = 0
      DisplayWidth = 0
      Position = 0
    end
    object ppDB493ppField2: TppField
      FieldAlias = 'ship_address'
      FieldName = 'ship_address'
      FieldLength = 50
      DisplayWidth = 50
      Position = 1
    end
    object ppDB493ppField3: TppField
      FieldAlias = 'Company_Icon'
      FieldName = 'Company_Icon'
      FieldLength = 0
      DataType = dtBLOB
      DisplayWidth = 10
      Position = 2
      Searchable = False
      Sortable = False
    end
    object ppDB493ppField4: TppField
      FieldAlias = 'SITE_INFO_ADD_1'
      FieldName = 'SITE_INFO_ADD_1'
      FieldLength = 50
      DisplayWidth = 50
      Position = 3
    end
    object ppDB493ppField5: TppField
      FieldAlias = 'SITE_INFO_ADD_2'
      FieldName = 'SITE_INFO_ADD_2'
      FieldLength = 50
      DisplayWidth = 50
      Position = 4
    end
    object ppDB493ppField6: TppField
      FieldAlias = 'SITE_INFO_ADD_3'
      FieldName = 'SITE_INFO_ADD_3'
      FieldLength = 50
      DisplayWidth = 50
      Position = 5
    end
    object ppDB493ppField7: TppField
      FieldAlias = 'SITE_INFO_PHONE'
      FieldName = 'SITE_INFO_PHONE'
      FieldLength = 30
      DisplayWidth = 30
      Position = 6
    end
  end
  object ppDB53: TppDBPipeline
    DataSource = Form4.DataSource1
    UserName = 'DB53'
    Left = 152
    Top = 100
    object ppDB53ppField1: TppField
      FieldAlias = 'PROD_CODE'
      FieldName = 'PROD_CODE'
      FieldLength = 5
      DisplayWidth = 10
      Position = 0
    end
    object ppDB53ppField2: TppField
      FieldAlias = 'CUSTOMER_PART_NUMBER'
      FieldName = 'CUSTOMER_PART_NUMBER'
      FieldLength = 20
      DisplayWidth = 24
      Position = 1
    end
    object ppDB53ppField3: TppField
      FieldAlias = 'CUSTOMER_PART_DESC'
      FieldName = 'CUSTOMER_PART_DESC'
      FieldLength = 40
      DisplayWidth = 53
      Position = 2
    end
    object ppDB53ppField4: TppField
      FieldAlias = 'CP_REV'
      FieldName = 'CP_REV'
      FieldLength = 5
      DisplayWidth = 8
      Position = 3
    end
    object ppDB53ppField5: TppField
      FieldAlias = 'CUST_CODE'
      FieldName = 'CUST_CODE'
      FieldLength = 5
      DisplayWidth = 16
      Position = 4
    end
    object ppDB53ppField6: TppField
      Alignment = taRightJustify
      FieldAlias = 'quantity_hand'
      FieldName = 'quantity_hand'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 16
      Position = 5
    end
    object ppDB53ppField7: TppField
      Alignment = taRightJustify
      FieldAlias = 'amount'
      FieldName = 'amount'
      FieldLength = 0
      DataType = dtDouble
      DisplayWidth = 16
      Position = 6
    end
  end
  object ppReport1: TppReport
    AutoStop = False
    DataPipeline = ppDB53
    PassSetting = psTwoPass
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = 'rport'
    PrinterSetup.PaperName = 'A4 210 x 297 '#27627#31859
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    PrinterSetup.PaperSize = 9
    SaveAsTemplate = True
    Template.FileName = 'R:\NIERP\Report\custpart_lucre.rtm'
    Units = utMillimeters
    DeviceType = 'Screen'
    OnPreviewFormCreate = ppReport1PreviewFormCreate
    Left = 184
    Top = 100
    Version = '6.03'
    mmColumnWidth = 0
    DataPipelineName = 'ppDB53'
    object ppHeaderBand1: TppHeaderBand
      mmBottomOffset = 0
      mmHeight = 35190
      mmPrintPosition = 0
      object ppVariable1: TppVariable
        UserName = 'Variable1'
        CalcOrder = 0
        CalcType = veReportStart
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = '宋体'
        Font.Size = 14
        Font.Style = [fsBold]
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 6085
        mmLeft = 52123
        mmTop = 3175
        mmWidth = 88106
        BandType = 0
      end
      object ppDBImage1: TppDBImage
        UserName = 'DBImage1'
        MaintainAspectRatio = False
        Stretch = True
        DataField = 'Company_Icon'
        DataPipeline = ppDB493
        GraphicType = 'Bitmap'
        ParentDataPipeline = False
        DataPipelineName = 'ppDB493'
        mmHeight = 13229
        mmLeft = 6350
        mmTop = 5292
        mmWidth = 17000
        BandType = 0
      end
      object ppSystemVariable2: TppSystemVariable
        UserName = 'SystemVariable2'
        VarType = vtPageSetDesc
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4233
        mmLeft = 169863
        mmTop = 15610
        mmWidth = 17463
        BandType = 0
      end
      object ppSystemVariable3: TppSystemVariable
        UserName = 'SystemVariable3'
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4128
        mmLeft = 169863
        mmTop = 20638
        mmWidth = 17568
        BandType = 0
      end
      object ppLabel1: TppLabel
        UserName = 'Label1'
        Caption = #20135#21697#31867#22411
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4128
        mmLeft = 8202
        mmTop = 30427
        mmWidth = 14393
        BandType = 0
      end
      object ppLabel2: TppLabel
        UserName = 'Label2'
        Caption = #23458#25143#37096#20214
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 28046
        mmTop = 30427
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel3: TppLabel
        UserName = 'Label3'
        Caption = #37096#20214#25551#36848
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 57944
        mmTop = 30427
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel4: TppLabel
        UserName = 'Label4'
        Caption = #20462#35746#26412
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 106098
        mmTop = 30427
        mmWidth = 10848
        BandType = 0
      end
      object ppLabel5: TppLabel
        UserName = 'Label5'
        Caption = #23458#25143#20195#30721
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 122767
        mmTop = 30427
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel6: TppLabel
        UserName = 'Label6'
        Caption = #24211#23384#25968#37327
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 142611
        mmTop = 30427
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel7: TppLabel
        UserName = 'Label7'
        Caption = #21512#35745#37329#39069
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        mmHeight = 4233
        mmLeft = 163777
        mmTop = 30427
        mmWidth = 14288
        BandType = 0
      end
      object ppLine2: TppLine
        UserName = 'Line2'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 5556
        mmTop = 34660
        mmWidth = 184150
        BandType = 0
      end
      object ppLine1: TppLine
        UserName = 'Line1'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 5556
        mmTop = 20108
        mmWidth = 184150
        BandType = 0
      end
      object ppLabel8: TppLabel
        UserName = 'Label8'
        Caption = #25104#21697#24211#23384#28165#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = '宋体'
        Font.Size = 12
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4763
        mmLeft = 83344
        mmTop = 11906
        mmWidth = 25400
        BandType = 0
      end
    end
    object ppDetailBand1: TppDetailBand
      mmBottomOffset = 0
      mmHeight = 3440
      mmPrintPosition = 0
      object ppDBText1: TppDBText
        UserName = 'DBText1'
        AutoSize = True
        DataField = 'PROD_CODE'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 14817
        mmTop = 0
        mmWidth = 3281
        BandType = 4
      end
      object ppDBText2: TppDBText
        UserName = 'DBText2'
        AutoSize = True
        DataField = 'CUSTOMER_PART_NUMBER'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 28840
        mmTop = 0
        mmWidth = 21908
        BandType = 4
      end
      object ppDBText3: TppDBText
        UserName = 'DBText3'
        AutoSize = True
        DataField = 'CUSTOMER_PART_DESC'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 57415
        mmTop = 0
        mmWidth = 43074
        BandType = 4
      end
      object ppDBText4: TppDBText
        UserName = 'DBText4'
        AutoSize = True
        DataField = 'CP_REV'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 110331
        mmTop = 0
        mmWidth = 4974
        BandType = 4
      end
      object ppDBText5: TppDBText
        UserName = 'DBText5'
        AutoSize = True
        DataField = 'CUST_CODE'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 125942
        mmTop = 0
        mmWidth = 7408
        BandType = 4
      end
      object ppDBText6: TppDBText
        UserName = 'DBText6'
        AutoSize = True
        DataField = 'quantity_hand'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 148961
        mmTop = 0
        mmWidth = 4763
        BandType = 4
      end
      object ppDBText7: TppDBText
        UserName = 'DBText7'
        AutoSize = True
        DataField = 'amount'
        DataPipeline = ppDB53
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB53'
        mmHeight = 3493
        mmLeft = 168275
        mmTop = 0
        mmWidth = 6350
        BandType = 4
      end
    end
    object ppFooterBand1: TppFooterBand
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object raCodeModule1: TraCodeModule
      ProgramStream = {
        01060F5472614576656E7448616E646C65720B50726F6772616D4E616D65060F
        5661726961626C65314F6E43616C630B50726F6772616D54797065070B747450
        726F63656475726506536F75726365066870726F636564757265205661726961
        626C65314F6E43616C63287661722056616C75653A2056617269616E74293B0D
        0A626567696E0D0A0D0A202056616C7565203A3D207472696D2844423439335B
        27436F6D70616E795F4E616D65275D293B0D0A656E643B0D0A0D436F6D706F6E
        656E744E616D6506095661726961626C6531094576656E744E616D6506064F6E
        43616C63074576656E74494402210000}
    end
  end
  object ppDB53_in: TppDBPipeline
    DataSource = Form2.DataSource1
    UserName = 'DB53_in'
    Left = 152
    Top = 136
  end
  object ppReport2: TppReport
    AutoStop = False
    DataPipeline = ppDB53_in
    PassSetting = psTwoPass
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = 'report2'
    PrinterSetup.PaperName = 'A4 210 x 297 '#27627#31859
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    PrinterSetup.PaperSize = 9
    SaveAsTemplate = True
    Template.FileName = 'R:\NIERP\Report\received_custpart.rtm'
    Units = utMillimeters
    DeviceType = 'Screen'
    OnPreviewFormCreate = ppReport2PreviewFormCreate
    Left = 184
    Top = 136
    Version = '6.03'
    mmColumnWidth = 0
    DataPipelineName = 'ppDB53_in'
    object ppHeaderBand2: TppHeaderBand
      mmBottomOffset = 0
      mmHeight = 31485
      mmPrintPosition = 0
      object ppLabel9: TppLabel
        UserName = 'Label9'
        Caption = #25104#21697#36827#20179#28165#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = '宋体'
        Font.Size = 12
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4763
        mmLeft = 81492
        mmTop = 10583
        mmWidth = 25400
        BandType = 0
      end
      object ppVariable2: TppVariable
        UserName = 'Variable2'
        CalcOrder = 0
        Font.Charset = GB2312_CHARSET
        Font.Color = clBlack
        Font.Name = '宋体'
        Font.Size = 14
        Font.Style = [fsBold]
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 6085
        mmLeft = 47890
        mmTop = 2646
        mmWidth = 91811
        BandType = 0
      end
      object ppDBImage2: TppDBImage
        UserName = 'DBImage2'
        MaintainAspectRatio = False
        Stretch = True
        DataField = 'Company_Icon'
        DataPipeline = ppDB493
        GraphicType = 'Bitmap'
        ParentDataPipeline = False
        DataPipelineName = 'ppDB493'
        mmHeight = 13229
        mmLeft = 6615
        mmTop = 5556
        mmWidth = 16933
        BandType = 0
      end
      object ppLine3: TppLine
        UserName = 'Line3'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 6350
        mmTop = 20108
        mmWidth = 183092
        BandType = 0
      end
      object ppSystemVariable1: TppSystemVariable
        UserName = 'SystemVariable1'
        VarType = vtPageSetDesc
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 171450
        mmTop = 15346
        mmWidth = 17463
        BandType = 0
      end
      object ppSystemVariable4: TppSystemVariable
        UserName = 'SystemVariable4'
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4128
        mmLeft = 171450
        mmTop = 20638
        mmWidth = 17568
        BandType = 0
      end
      object ppLabel11: TppLabel
        UserName = 'Label11'
        Caption = #24037#20316#23450#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 25929
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel12: TppLabel
        UserName = 'Label12'
        Caption = #20135#21697#31867#22411
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 52917
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel13: TppLabel
        UserName = 'Label13'
        Caption = #20301#32622
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 70379
        mmTop = 27252
        mmWidth = 7938
        BandType = 0
      end
      object ppLabel14: TppLabel
        UserName = 'Label14'
        Caption = #21046#36896#26085#26399
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 81227
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel15: TppLabel
        UserName = 'Label15'
        Caption = #38468#21152#21442#32771
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 112977
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel16: TppLabel
        UserName = 'Label16'
        Caption = #29616#26377#24211#23384
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 139171
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel17: TppLabel
        UserName = 'Label17'
        Caption = #36827#20179#25968#37327
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 156104
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel18: TppLabel
        UserName = 'Label18'
        Caption = #26368#26032#20215#26684
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 173038
        mmTop = 27252
        mmWidth = 14288
        BandType = 0
      end
    end
    object ppDetailBand2: TppDetailBand
      mmBottomOffset = 0
      mmHeight = 3440
      mmPrintPosition = 0
      object ppDBText13: TppDBText
        UserName = 'DBText13'
        AutoSize = True
        DataField = 'PROD_CODE'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 55563
        mmTop = 0
        mmWidth = 3281
        BandType = 4
      end
      object ppDBText14: TppDBText
        UserName = 'DBText14'
        AutoSize = True
        DataField = 'CODE'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 69850
        mmTop = 0
        mmWidth = 8467
        BandType = 4
      end
      object ppDBText15: TppDBText
        UserName = 'DBText15'
        AutoSize = True
        DataField = 'MFG_DATE'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 82286
        mmTop = 0
        mmWidth = 13018
        BandType = 4
      end
      object ppDBText16: TppDBText
        UserName = 'DBText16'
        AutoSize = True
        DataField = 'QTY_ON_HAND'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 147373
        mmTop = 0
        mmWidth = 4763
        BandType = 4
      end
      object ppDBText17: TppDBText
        UserName = 'DBText17'
        AutoSize = True
        DataField = 'QUANTITY'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 164571
        mmTop = 0
        mmWidth = 4763
        BandType = 4
      end
      object ppDBText18: TppDBText
        UserName = 'DBText18'
        AutoSize = True
        DataField = 'REFERENCE_NUMBER'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 111919
        mmTop = 0
        mmWidth = 19897
        BandType = 4
      end
      object ppDBText12: TppDBText
        UserName = 'DBText12'
        AutoSize = True
        DataField = 'WORK_ORDER_NUMBER'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 22490
        mmTop = 0
        mmWidth = 22013
        BandType = 4
      end
      object ppDBText19: TppDBText
        UserName = 'DBText19'
        AutoSize = True
        DataField = 'LATEST_PRICE'
        DataPipeline = ppDB53_in
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB53_in'
        mmHeight = 3493
        mmLeft = 181505
        mmTop = 0
        mmWidth = 3175
        BandType = 4
      end
    end
    object ppFooterBand2: TppFooterBand
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object ppGroup1: TppGroup
      BreakName = 'CUST_CODE'
      DataPipeline = ppDB53_in
      KeepTogether = True
      UserName = 'Group1'
      mmNewColumnThreshold = 0
      mmNewPageThreshold = 0
      DataPipelineName = 'ppDB53_in'
      object ppGroupHeaderBand1: TppGroupHeaderBand
        mmBottomOffset = 0
        mmHeight = 5821
        mmPrintPosition = 0
        object ppDBText8: TppDBText
          UserName = 'DBText8'
          AutoSize = True
          DataField = 'CUST_CODE'
          DataPipeline = ppDB53_in
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = [fsBold, fsUnderline]
          Transparent = True
          DataPipelineName = 'ppDB53_in'
          mmHeight = 3493
          mmLeft = 23019
          mmTop = 1058
          mmWidth = 6879
          BandType = 3
          GroupNo = 0
        end
        object ppLabel10: TppLabel
          UserName = 'Label10'
          Caption = #23458#25143#20195#30721':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          Transparent = True
          mmHeight = 3440
          mmLeft = 7144
          mmTop = 1058
          mmWidth = 12700
          BandType = 3
          GroupNo = 0
        end
      end
      object ppGroupFooterBand1: TppGroupFooterBand
        mmBottomOffset = 0
        mmHeight = 1381
        mmPrintPosition = 0
      end
    end
    object ppGroup2: TppGroup
      BreakName = 'CUSTOMER_PART_NUMBER'
      DataPipeline = ppDB53_in
      KeepTogether = True
      UserName = 'Group2'
      mmNewColumnThreshold = 0
      mmNewPageThreshold = 0
      DataPipelineName = 'ppDB53_in'
      object ppGroupHeaderBand2: TppGroupHeaderBand
        mmBottomOffset = 0
        mmHeight = 4763
        mmPrintPosition = 0
        object ppDBText9: TppDBText
          UserName = 'DBText9'
          AutoSize = True
          DataField = 'CUSTOMER_PART_NUMBER'
          DataPipeline = ppDB53_in
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = [fsUnderline]
          Transparent = True
          DataPipelineName = 'ppDB53_in'
          mmHeight = 3493
          mmLeft = 27781
          mmTop = 529
          mmWidth = 22754
          BandType = 3
          GroupNo = 1
        end
        object ppLabel20: TppLabel
          UserName = 'Label20'
          Caption = #23458#25143#37096#20214':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          TextAlignment = taRightJustified
          Transparent = True
          mmHeight = 3440
          mmLeft = 11906
          mmTop = 529
          mmWidth = 12700
          BandType = 3
          GroupNo = 1
        end
      end
      object ppGroupFooterBand2: TppGroupFooterBand
        mmBottomOffset = 0
        mmHeight = 4498
        mmPrintPosition = 0
        object ppLine4: TppLine
          UserName = 'Line4'
          Weight = 0.75
          mmHeight = 265
          mmLeft = 6350
          mmTop = 0
          mmWidth = 183092
          BandType = 5
          GroupNo = 1
        end
        object ppLine5: TppLine
          UserName = 'Line5'
          Weight = 0.75
          mmHeight = 265
          mmLeft = 6350
          mmTop = 4233
          mmWidth = 183092
          BandType = 5
          GroupNo = 1
        end
        object ppLabel19: TppLabel
          UserName = 'Label19'
          Caption = #23567#35745':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          Transparent = True
          mmHeight = 3440
          mmLeft = 126736
          mmTop = 529
          mmWidth = 6879
          BandType = 5
          GroupNo = 1
        end
        object ppDBCalc1: TppDBCalc
          UserName = 'DBCalc1'
          DataField = 'QTY_ON_HAND'
          DataPipeline = ppDB53_in
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          ResetGroup = ppGroup2
          TextAlignment = taRightJustified
          Transparent = True
          DataPipelineName = 'ppDB53_in'
          mmHeight = 3440
          mmLeft = 134938
          mmTop = 529
          mmWidth = 17198
          BandType = 5
          GroupNo = 1
        end
        object ppDBCalc2: TppDBCalc
          UserName = 'DBCalc2'
          DataField = 'QUANTITY'
          DataPipeline = ppDB53_in
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          ResetGroup = ppGroup2
          TextAlignment = taRightJustified
          Transparent = True
          DataPipelineName = 'ppDB53_in'
          mmHeight = 3440
          mmLeft = 152136
          mmTop = 529
          mmWidth = 17198
          BandType = 5
          GroupNo = 1
        end
      end
    end
    object raCodeModule2: TraCodeModule
      ProgramStream = {
        01060F5472614576656E7448616E646C65720B50726F6772616D4E616D65060F
        5661726961626C65324F6E43616C630B50726F6772616D54797065070B747450
        726F63656475726506536F75726365066970726F636564757265205661726961
        626C65324F6E43616C63287661722056616C75653A2056617269616E74293B0D
        0A626567696E0D0A0D0A202056616C7565203A3D7472696D2844423439335B27
        436F6D70616E795F4E616D65275D293B0D0A0D0A656E643B0D0A0D436F6D706F
        6E656E744E616D6506095661726961626C6532094576656E744E616D6506064F
        6E43616C63074576656E74494402210000}
    end
  end
  object ppDB52: TppDBPipeline
    DataSource = Form3.DataSource1
    UserName = 'DB52'
    Left = 152
    Top = 173
    object ppDB52ppField1: TppField
      FieldAlias = 'SALES_ORDER'
      FieldName = 'SALES_ORDER'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 0
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField2: TppField
      FieldAlias = 'delivery_no'
      FieldName = 'delivery_no'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 1
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField3: TppField
      FieldAlias = 'CUSTOMER_PART_NUMBER'
      FieldName = 'CUSTOMER_PART_NUMBER'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 2
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField4: TppField
      FieldAlias = 'CUSTOMER_PART_DESC'
      FieldName = 'CUSTOMER_PART_DESC'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 3
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField5: TppField
      FieldAlias = 'CP_REV'
      FieldName = 'CP_REV'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 4
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField6: TppField
      FieldAlias = 'PROD_CODE'
      FieldName = 'PROD_CODE'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 5
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField7: TppField
      FieldAlias = 'CUST_CODE'
      FieldName = 'CUST_CODE'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 6
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField8: TppField
      FieldAlias = 'WAREHOUSE_CODE'
      FieldName = 'WAREHOUSE_CODE'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 7
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField9: TppField
      FieldAlias = 'CODE'
      FieldName = 'CODE'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 8
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField10: TppField
      FieldAlias = 'QUAN_SHP'
      FieldName = 'QUAN_SHP'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 9
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField11: TppField
      FieldAlias = 'part_price'
      FieldName = 'part_price'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 10
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField12: TppField
      FieldAlias = 'amount'
      FieldName = 'amount'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 11
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField13: TppField
      FieldAlias = 'DATE_SHIPPED'
      FieldName = 'DATE_SHIPPED'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 12
      Searchable = False
      Sortable = False
    end
    object ppDB52ppField14: TppField
      FieldAlias = 'SHIPMENT_NO'
      FieldName = 'SHIPMENT_NO'
      FieldLength = 0
      DataType = dtNotKnown
      DisplayWidth = 0
      Position = 13
      Searchable = False
      Sortable = False
    end
  end
  object ppReport3: TppReport
    AutoStop = False
    DataPipeline = ppDB52
    PassSetting = psTwoPass
    PrinterSetup.BinName = 'Default'
    PrinterSetup.DocumentName = 'Report'
    PrinterSetup.PaperName = 'A4 210 x 297 '#27627#31859
    PrinterSetup.PrinterName = 'Default'
    PrinterSetup.mmMarginBottom = 6350
    PrinterSetup.mmMarginLeft = 6350
    PrinterSetup.mmMarginRight = 6350
    PrinterSetup.mmMarginTop = 6350
    PrinterSetup.mmPaperHeight = 297000
    PrinterSetup.mmPaperWidth = 210000
    PrinterSetup.PaperSize = 9
    SaveAsTemplate = True
    Template.FileName = 'R:\NIERP\Report\exhale_custpart.rtm'
    Units = utMillimeters
    DeviceType = 'Screen'
    OnPreviewFormCreate = ppReport3PreviewFormCreate
    Left = 184
    Top = 173
    Version = '6.03'
    mmColumnWidth = 0
    DataPipelineName = 'ppDB52'
    object ppHeaderBand3: TppHeaderBand
      mmBottomOffset = 0
      mmHeight = 30692
      mmPrintPosition = 0
      object ppDBImage3: TppDBImage
        UserName = 'DBImage3'
        MaintainAspectRatio = False
        Stretch = True
        DataField = 'Company_Icon'
        DataPipeline = ppDB493
        GraphicType = 'Bitmap'
        ParentDataPipeline = False
        DataPipelineName = 'ppDB493'
        mmHeight = 13229
        mmLeft = 6350
        mmTop = 6085
        mmWidth = 16933
        BandType = 0
      end
      object ppLabel22: TppLabel
        UserName = 'Label22'
        Caption = #25104#21697#20986#20179#28165#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 12
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4868
        mmLeft = 86784
        mmTop = 11377
        mmWidth = 25400
        BandType = 0
      end
      object ppVariable3: TppVariable
        UserName = 'Variable3'
        CalcOrder = 0
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 14
        Font.Style = [fsBold]
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 6085
        mmLeft = 53975
        mmTop = 3175
        mmWidth = 92340
        BandType = 0
      end
      object ppLine6: TppLine
        UserName = 'Line6'
        Weight = 0.75
        mmHeight = 265
        mmLeft = 5292
        mmTop = 20373
        mmWidth = 186267
        BandType = 0
      end
      object ppSystemVariable5: TppSystemVariable
        UserName = 'SystemVariable5'
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4233
        mmLeft = 174361
        mmTop = 20638
        mmWidth = 17463
        BandType = 0
      end
      object ppSystemVariable6: TppSystemVariable
        UserName = 'SystemVariable6'
        VarType = vtPageSetDesc
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4128
        mmLeft = 174414
        mmTop = 16140
        mmWidth = 17357
        BandType = 0
      end
      object ppLabel24: TppLabel
        UserName = 'Label24'
        Caption = #20215#26684
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 159809
        mmTop = 26458
        mmWidth = 7144
        BandType = 0
      end
      object ppLabel25: TppLabel
        UserName = 'Label25'
        Caption = #35013#36816#26085#26399
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 98954
        mmTop = 26458
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel26: TppLabel
        UserName = 'Label26'
        Caption = #20986#20179#25968#37327
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4233
        mmLeft = 118534
        mmTop = 26458
        mmWidth = 14288
        BandType = 0
      end
      object ppLabel27: TppLabel
        UserName = 'Label27'
        Caption = #20301#32622
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4128
        mmLeft = 87048
        mmTop = 26458
        mmWidth = 7197
        BandType = 0
      end
      object ppLabel28: TppLabel
        UserName = 'Label28'
        Caption = #20135#21697#31867#22411
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4128
        mmLeft = 70115
        mmTop = 26458
        mmWidth = 14393
        BandType = 0
      end
      object ppLabel29: TppLabel
        UserName = 'Label29'
        Caption = #38144#21806#35746#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4128
        mmLeft = 52388
        mmTop = 26458
        mmWidth = 14393
        BandType = 0
      end
      object ppLabel30: TppLabel
        UserName = 'Label30'
        Caption = #35013#31665#21333
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        TextAlignment = taCentered
        Transparent = True
        mmHeight = 4233
        mmLeft = 32015
        mmTop = 26458
        mmWidth = 10848
        BandType = 0
      end
      object ppLabel31: TppLabel
        UserName = 'Label31'
        Caption = #37329#39069
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4128
        mmLeft = 173302
        mmTop = 26458
        mmWidth = 7197
        BandType = 0
      end
      object ppLabel32: TppLabel
        UserName = 'Label32'
        Caption = #25351#27966#25209#27425
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 10
        Font.Style = []
        Transparent = True
        mmHeight = 4233
        mmLeft = 138377
        mmTop = 26458
        mmWidth = 14288
        BandType = 0
      end
    end
    object ppDetailBand3: TppDetailBand
      mmBottomOffset = 0
      mmHeight = 3440
      mmPrintPosition = 0
      object ppDBText21: TppDBText
        UserName = 'DBText21'
        AutoSize = True
        DataField = 'delivery_no'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 28575
        mmTop = 0
        mmWidth = 15875
        BandType = 4
      end
      object ppDBText22: TppDBText
        UserName = 'DBText22'
        AutoSize = True
        DataField = 'SALES_ORDER'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 52388
        mmTop = 0
        mmWidth = 15240
        BandType = 4
      end
      object ppDBText23: TppDBText
        UserName = 'DBText23'
        AutoSize = True
        DataField = 'PROD_CODE'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 75936
        mmTop = 0
        mmWidth = 3281
        BandType = 4
      end
      object ppDBText24: TppDBText
        UserName = 'DBText24'
        AutoSize = True
        DataField = 'CODE'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 86784
        mmTop = 0
        mmWidth = 7620
        BandType = 4
      end
      object ppDBText25: TppDBText
        UserName = 'DBText25'
        AutoSize = True
        DataField = 'QUAN_SHP'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 126471
        mmTop = 0
        mmWidth = 4763
        BandType = 4
      end
      object ppDBText26: TppDBText
        UserName = 'DBText26'
        AutoSize = True
        DataField = 'part_price'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 160602
        mmTop = 0
        mmWidth = 5609
        BandType = 4
      end
      object ppDBText27: TppDBText
        UserName = 'DBText27'
        AutoSize = True
        DataField = 'DATE_SHIPPED'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 99748
        mmTop = 0
        mmWidth = 14393
        BandType = 4
      end
      object ppDBText11: TppDBText
        UserName = 'DBText11'
        AutoSize = True
        DataField = 'amount'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 174361
        mmTop = 0
        mmWidth = 7197
        BandType = 4
      end
      object ppDBText28: TppDBText
        UserName = 'DBText28'
        AutoSize = True
        DataField = 'SHIPMENT_NO'
        DataPipeline = ppDB52
        Font.Charset = GB2312_CHARSET
        Font.Color = clWindowText
        Font.Name = '宋体'
        Font.Size = 8
        Font.Style = []
        TextAlignment = taRightJustified
        Transparent = True
        DataPipelineName = 'ppDB52'
        mmHeight = 3493
        mmLeft = 147109
        mmTop = 0
        mmWidth = 1588
        BandType = 4
      end
    end
    object ppFooterBand3: TppFooterBand
      mmBottomOffset = 0
      mmHeight = 0
      mmPrintPosition = 0
    end
    object ppGroup3: TppGroup
      BreakName = 'CUST_CODE'
      DataPipeline = ppDB52
      KeepTogether = True
      UserName = 'Group3'
      mmNewColumnThreshold = 0
      mmNewPageThreshold = 0
      DataPipelineName = 'ppDB52'
      object ppGroupHeaderBand3: TppGroupHeaderBand
        mmBottomOffset = 0
        mmHeight = 5821
        mmPrintPosition = 0
        object ppDBText10: TppDBText
          UserName = 'DBText10'
          AutoSize = True
          DataField = 'CUST_CODE'
          DataPipeline = ppDB52
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = [fsBold, fsUnderline]
          Transparent = True
          DataPipelineName = 'ppDB52'
          mmHeight = 3493
          mmLeft = 24077
          mmTop = 1058
          mmWidth = 6879
          BandType = 3
          GroupNo = 0
        end
        object ppLabel21: TppLabel
          UserName = 'Label21'
          Caption = #23458#25143#20195#30721':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          Transparent = True
          mmHeight = 3493
          mmLeft = 9525
          mmTop = 1058
          mmWidth = 12700
          BandType = 3
          GroupNo = 0
        end
      end
      object ppGroupFooterBand3: TppGroupFooterBand
        mmBottomOffset = 0
        mmHeight = 0
        mmPrintPosition = 0
      end
    end
    object ppGroup4: TppGroup
      BreakName = 'CUSTOMER_PART_NUMBER'
      DataPipeline = ppDB52
      KeepTogether = True
      UserName = 'Group4'
      mmNewColumnThreshold = 0
      mmNewPageThreshold = 0
      DataPipelineName = 'ppDB52'
      object ppGroupHeaderBand4: TppGroupHeaderBand
        mmBottomOffset = 0
        mmHeight = 5027
        mmPrintPosition = 0
        object ppDBText20: TppDBText
          UserName = 'DBText20'
          AutoSize = True
          DataField = 'CUSTOMER_PART_NUMBER'
          DataPipeline = ppDB52
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = [fsUnderline]
          Transparent = True
          DataPipelineName = 'ppDB52'
          mmHeight = 3493
          mmLeft = 28575
          mmTop = 794
          mmWidth = 22754
          BandType = 3
          GroupNo = 1
        end
        object ppLabel23: TppLabel
          UserName = 'Label23'
          Caption = #23458#25143#37096#20214':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = [fsUnderline]
          TextAlignment = taCentered
          Transparent = True
          mmHeight = 3493
          mmLeft = 14024
          mmTop = 794
          mmWidth = 12700
          BandType = 3
          GroupNo = 1
        end
      end
      object ppGroupFooterBand4: TppGroupFooterBand
        mmBottomOffset = 0
        mmHeight = 5292
        mmPrintPosition = 0
        object ppLine7: TppLine
          UserName = 'Line7'
          Weight = 0.75
          mmHeight = 265
          mmLeft = 5292
          mmTop = 0
          mmWidth = 186267
          BandType = 5
          GroupNo = 1
        end
        object ppLine8: TppLine
          UserName = 'Line8'
          Weight = 0.75
          mmHeight = 265
          mmLeft = 5292
          mmTop = 5027
          mmWidth = 186267
          BandType = 5
          GroupNo = 1
        end
        object ppDBCalc3: TppDBCalc
          UserName = 'DBCalc3'
          DataField = 'QUAN_SHP'
          DataPipeline = ppDB52
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          ResetGroup = ppGroup4
          TextAlignment = taRightJustified
          Transparent = True
          DataPipelineName = 'ppDB52'
          mmHeight = 3440
          mmLeft = 113771
          mmTop = 794
          mmWidth = 17463
          BandType = 5
          GroupNo = 1
        end
        object ppDBCalc4: TppDBCalc
          UserName = 'DBCalc4'
          DataField = 'amount'
          DataPipeline = ppDB52
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          ResetGroup = ppGroup4
          TextAlignment = taRightJustified
          Transparent = True
          DataPipelineName = 'ppDB52'
          mmHeight = 3440
          mmLeft = 164307
          mmTop = 794
          mmWidth = 17198
          BandType = 5
          GroupNo = 1
        end
        object ppLabel33: TppLabel
          UserName = 'Label33'
          Caption = #23567#35745':'
          Font.Charset = GB2312_CHARSET
          Font.Color = clWindowText
          Font.Name = '宋体'
          Font.Size = 8
          Font.Style = []
          TextAlignment = taRightJustified
          Transparent = True
          mmHeight = 3493
          mmLeft = 105410
          mmTop = 794
          mmWidth = 6773
          BandType = 5
          GroupNo = 1
        end
      end
    end
    object raCodeModule3: TraCodeModule
      ProgramStream = {
        01060F5472614576656E7448616E646C65720B50726F6772616D4E616D65060F
        5661726961626C65334F6E43616C630B50726F6772616D54797065070B747450
        726F63656475726506536F75726365066A70726F636564757265205661726961
        626C65334F6E43616C63287661722056616C75653A2056617269616E74293B0D
        0A626567696E0D0A0D0A202056616C7565203A3D207472696D2844423439335B
        27436F6D70616E795F4E616D65275D293B0D0A0D0A656E643B0D0A0D436F6D70
        6F6E656E744E616D6506095661726961626C6533094576656E744E616D650606
        4F6E43616C63074576656E74494402210000}
    end
  end
end
