object Form6: TForm6
  Left = 255
  Top = 188
  BorderIcons = [biSystemMenu]
  BorderStyle = bsDialog
  ClientHeight = 385
  ClientWidth = 586
  Color = clBtnFace
  Font.Charset = GB2312_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'ËÎÌו'
  Font.Style = []
  OldCreateOrder = False
  Position = poScreenCenter
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object Label1: TLabel
    Left = 30
    Top = 117
    Width = 72
    Height = 13
    Alignment = taRightJustify
    Caption = '   '#19968#33324#35760#20107#26412':'
  end
  object Label2: TLabel
    Left = 29
    Top = 238
    Width = 72
    Height = 13
    Alignment = taRightJustify
    Caption = '   '#20132#36135#35760#20107#26412':'
  end
  object Label3: TLabel
    Left = 92
    Top = 11
    Width = 48
    Height = 13
    Alignment = taRightJustify
    Caption = '   '#20379#24212#21830':'
  end
  object Label4: TLabel
    Left = 62
    Top = 38
    Width = 78
    Height = 13
    Alignment = taRightJustify
    Caption = '     '#24080#30446#32852#32476#20154':'
  end
  object Label5: TLabel
    Left = 271
    Top = 38
    Width = 36
    Height = 13
    Alignment = taRightJustify
    Caption = '   '#30005#35805':'
  end
  object Label6: TLabel
    Left = 104
    Top = 61
    Width = 36
    Height = 13
    Alignment = taRightJustify
    Caption = '   '#22320#22336':'
  end
  object Memo1: TMemo
    Left = 16
    Top = 139
    Width = 555
    Height = 89
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 0
  end
  object Memo2: TMemo
    Left = 16
    Top = 259
    Width = 555
    Height = 89
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 1
  end
  object Edit2: TEdit
    Left = 143
    Top = 8
    Width = 288
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 2
  end
  object Edit1: TEdit
    Left = 143
    Top = 34
    Width = 121
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 3
  end
  object Edit3: TEdit
    Left = 311
    Top = 34
    Width = 121
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 4
  end
  object Edit4: TEdit
    Left = 143
    Top = 57
    Width = 289
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 5
  end
  object Edit5: TEdit
    Left = 143
    Top = 82
    Width = 289
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 6
  end
  object Edit6: TEdit
    Left = 143
    Top = 107
    Width = 289
    Height = 21
    Color = cl3DLight
    ReadOnly = True
    TabOrder = 7
  end
  object Button1: TButton
    Left = 241
    Top = 355
    Width = 75
    Height = 25
    Caption = #20851#38381
    ModalResult = 1
    TabOrder = 8
  end
end
