object Frm_tree: TFrm_tree
  Left = 215
  Top = 130
  Width = 394
  Height = 341
  BorderIcons = [biSystemMenu]
  Caption = 'tree'
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = #23435#20307
  Font.Style = []
  OldCreateOrder = False
  OnKeyDown = FormKeyDown
  PixelsPerInch = 96
  TextHeight = 13
  object TreeView1: TTreeView
    Left = 0
    Top = 0
    Width = 386
    Height = 311
    Align = alClient
    Indent = 19
    TabOrder = 0
    OnDblClick = TreeView1DblClick
    OnKeyDown = FormKeyDown
  end
end
