SET IDENTITY_INSERT data0514 ON
insert into Data0514(RKEY,FASSET_TYPE,depr_mthd_ptr,expected_life,expected_surplus_rate,prechar1)
select RKEY,FASSET_TYPE,depr_mthd_ptr,expected_life,expected_surplus_rate,prechar1 from  [192.168.1.253].sj_v20_live.dbo.data0514  as KD0514
WHERE NOT EXISTS(SELECT RKEY FROM Data0514 WHERE Data0514.RKEY=KD0514.RKEY)
go
SET IDENTITY_INSERT data0514 Off


SET IDENTITY_INSERT data0515 ON
insert into Data0515(RKEY,FASSET_ALT_TYPE,ALT_FLAG)
select RKEY,FASSET_ALT_TYPE,ALT_FLAG from  [192.168.1.253].sj_v20_live.dbo.data0515  as KD0515
WHERE NOT EXISTS(SELECT RKEY FROM Data0515 WHERE Data0515.RKEY=KD0515.RKEY)
go
SET IDENTITY_INSERT data0515 Off



SET IDENTITY_INSERT data0516 ON
insert into Data0516(RKEY,FASSET_STATUS,IN_DEPRECIATION)
select RKEY,FASSET_STATUS,IN_DEPRECIATION from  [192.168.1.253].sj_v20_live.dbo.data0516  as KD0516
WHERE NOT EXISTS(SELECT RKEY FROM Data0516 WHERE Data0516.RKEY=KD0516.RKEY)
go
SET IDENTITY_INSERT data0516 Off

SET IDENTITY_INSERT data0516 ON
insert into Data0516(RKEY,FASSET_STATUS,IN_DEPRECIATION)
select RKEY,FASSET_STATUS,IN_DEPRECIATION from  [192.168.1.253].sj_v20_live.dbo.data0516  as KD0516
WHERE NOT EXISTS(SELECT RKEY FROM Data0516 WHERE Data0516.RKEY=KD0516.RKEY)
go
SET IDENTITY_INSERT data0516 Off




SET IDENTITY_INSERT data0517 ON
insert into Data0517(RKEY,FASSET_CODE,FASSET_NAME,FASSET_DESC,FASSET_TYPE_PTR,DEPT_PTR,ALT_TYPE_PTR,
STATUS_PTR,ORIGINAL_VALUE,SUMMED_DEPRE,NET_VALUE,LOCATION,BOOK_DATE,SURPLUS_RATE,SURPLUS,
DEPRE_MTHD_PTR,EXPECTED_LIFE_MONTHS,DEPRED_MONTHS,LOADING_UNIT,MONTH_DEPRE_RATE,MONTH_DEPRE_AMT,
DEPRE_ACCT_PTR,YEAR_ORGI_VALUE_OPEN,YEAR_ORGI_VALUE_INCREASE,YEAR_ORGI_VALUE_DECREASE,YEAR_DEPRE_SUMMED_OPEN,
YEAR_DEPRE_SUMMED_INCREASE,YEAR_DEPRE_SUMMED_DECREASE,REMARK,active_flag,
fasset_gl_ptr,faccu_depr_gl_ptr,depr_rate_method,voucher_ptr,id_code,ORIG_SUMMED_DEPRE,
orig_original_value)
select RKEY,FASSET_CODE,cast(FASSET_NAME as varchar(30)) as FASSET_NAME ,cast(FASSET_DESC as varchar(40)) as FASSET_DESC,FASSET_TYPE_PTR,DEPT_PTR,ALT_TYPE_PTR,
STATUS_PTR,ORIGINAL_VALUE,SUMMED_DEPRE,NET_VALUE,LOCATION,BOOK_DATE,SURPLUS_RATE,SURPLUS,
DEPRE_MTHD_PTR,EXPECTED_LIFE_MONTHS,DEPRED_MONTHS,LOADING_UNIT,MONTH_DEPRE_RATE,MONTH_DEPRE_AMT,
DEPRE_ACCT_PTR,YEAR_ORGI_VALUE_OPEN,YEAR_ORGI_VALUE_INCREASE,YEAR_ORGI_VALUE_DECREASE,YEAR_DEPRE_SUMMED_OPEN,
YEAR_DEPRE_SUMMED_INCREASE,YEAR_DEPRE_SUMMED_DECREASE,REMARK,active_flag,
fasset_gl_ptr,faccu_depr_gl_ptr,depr_rate_method,voucher_ptr,id_code,ORIG_SUMMED_DEPRE,
orig_original_value from  [192.168.1.253].sj_v20_live.dbo.data0517 as KD0517
WHERE NOT EXISTS(SELECT RKEY FROM Data0517 WHERE Data0517.RKEY=KD0517.RKEY)
SET IDENTITY_INSERT data0517 off



SET IDENTITY_INSERT data0325 ON
insert into data0325(rkey,fasset_ptr,curr_ptr,d327_ptr,ex_rate,orig_curr_orig_value)
select rkey,fasset_ptr,curr_ptr,d327_ptr,ex_rate,orig_curr_orig_value from  [192.168.1.253].sj_v20_live.dbo.data0325 as KD0325
WHERE NOT EXISTS(SELECT RKEY FROM Data0325 WHERE Data0325.RKEY=KD0325.RKEY)
go
SET IDENTITY_INSERT data0325 Off

SET IDENTITY_INSERT data0326 ON
insert into data0326(rkey,fasset_ptr,dept_ptr,FACCU_DEPT_GL_PTR,d327_ptr,PERCENTS)
select rkey,fasset_ptr, case when dept_ptr=244  then 245 else dept_ptr end as dept_ptr,FACCU_DEPT_GL_PTR,d327_ptr,PERCENTS
 from  [192.168.1.253].sj_v20_live.dbo.data0326 as KD0326
WHERE NOT EXISTS(SELECT RKEY FROM data0326 WHERE data0326.RKEY=KD0326.RKEY)
go
SET IDENTITY_INSERT data0326 Off




select * from  data0034 where rkey =245
select * from [192.168.1.253].sj_v20_live.dbo.data0326

sp_help  data0326

rkey,fasset_ptr,dept_ptr,FACCU_DEPT_GL_PTR,d327_ptr,PERCENTS


select RKEY,FASSET_TYPE,depr_mthd_ptr,expected_life,expected_surplus_rate,prechar1 from  [192.168.1.253].sj_v20_live.dbo.data0514  as KD0514

sp_help data0516
select RKEY,FASSET_TYPE,depr_mthd_ptr,expected_life,expected_surplus_rate,prechar1