


SET IDENTITY_INSERT data0017 ON
insert into Data0017( RKEY,INV_PART_NUMBER,INV_NAME,INV_DESCRIPTION,
GROUP_PTR,P_M,S_B_N,INSPECT,STOP_PURCH,MIX_PARTS,PHY_COUNT_METHOD,BOM_FLAG,COST_METHOD,
STOCK_UNIT_PTR,PURCH_UNIT_PTR,PREF_SUPPLIER_PTR,STOCK_PURCH,STOCK_QUOTE,STD_COST,SHELF_LIFE,AVL_FLAG,
CONSIGNMENT_FLAG,ACTIVE_FLAG,QUAN_ON_HAND,QUAN_ASSIGN,AUTO_PURCHASE_FLAG ,CRITICAL_MATL_FLAG)
select RKEY,INV_PART_NUMBER,INV_NAME,INV_DESCRIPTION,
GROUP_PTR,P_M,S_B_N,INSPECT,STOP_PURCH,MIX_PARTS,PHY_COUNT_METHOD,BOM_FLAG,COST_METHOD,
STOCK_UNIT_PTR,PURCH_UNIT_PTR,PREF_SUPPLIER_PTR,STOCK_PURCH,STOCK_QUOTE,STD_COST,SHELF_LIFE,AVL_FLAG,
CONSIGNMENT_FLAG,ACTIVE_FLAG,QUAN_ON_HAND,QUAN_ASSIGN,0 as AUTO_PURCHASE_FLAG,0 as CRITICAL_MATL_FLAG from [192.168.1.253].sj_v20_live.dbo.data0017 as KD0017
WHERE NOT EXISTS(SELECT RKEY FROM Data0017  WHERE Data0017.RKEY=KD0017.RKEY)
go
set identity_insert data0017 off



SET IDENTITY_INSERT data0456 on
insert into data0456(RKEY,GRN_NUMBER,warehouse_ptr,SUPP_PTR,PO_PTR,
TTYPE,STATUS,CREATE_DATE,CREATE_BY, ship_DATE,
AUDITED_BY,AUDITED_DATE,REF_NUMBER,PRINTED,currency_ptr,exch_rate)
select data0456.RKEY,GRN_NUMBER,2 as warehouse_ptr,SUPP_PTR,
case when PO_PTR =0 then 143 else PO_PTR end as po_ptr ,
TTYPE,data0456.STATUS,CREATE_DATE,CREATE_BY, case when InputDate IS null then CREATE_DATE else InputDate end as ship_DATE,
AUDITED_BY,AUDITED_DATE,REF_NUMBER,PRINTED,case when data0070.currency_ptr IS null  then 1 else  data0070.currency_ptr end  as currency_ptr,
case when data0070.EXCHANGE_RATE IS null then 1 else EXCHANGE_RATE end  as exch_rate
 from [192.168.1.253].sj_v20_live.dbo.data0456
 left join [192.168.1.253].sj_v20_live.dbo.data0070 on Data0456.PO_PTR=data0070.RKEY 
where (PO_PTR in (select RKEY from Data0070)  or  data0456.RKEY in  ( select GRN_PTR from [192.168.1.253].sj_v20_live.dbo.Data0022 
where QUAN_ON_HAND>0 and SOURCE_PTR is null)) and PO_PTR in(select RKEY from Data0070 where PO_TYPE in ('M','S')) 

SET IDENTITY_INSERT data0456 off
go







  
 SET IDENTITY_INSERT data0022 on
insert into data0022(RKEY,INVENTORY_PTR,GRN_PTR,SOURCE_PTR,SUPPLIER_PTR,LOCATION_PTR,QUANTITY,PRICE,DISCOUNT,QUAN_TO_BE_SHIPPED,
QUAN_TO_BE_STOCKED,QUAN_RETURNED,QUAN_SCRAPPED,TTYPE,TDATE,LOCATION_PTR_FROM,PACKING_SLIP_FLAG,QUAN_STOCKED,
QUAN_ISSUED_TO_FACT,QUAN_RTNED_FM_FACT,QUAN_ON_HAND,BARCODE_ID,EXPIRE_DATE,SUPPLIER2,TAX_2,tax_price)
select data0022.RKEY,INVENTORY_PTR,GRN_PTR,SOURCE_PTR,SUPPLIER_PTR,  LOCATION_PTR,QUANTITY,PRICE,DISCOUNT,QUAN_TO_BE_SHIPPED,
QUAN_TO_BE_STOCKED,QUAN_RETURNED,QUAN_SCRAPPED,data0022.TTYPE,TDATE,data0017.STOCK_UNIT_PTR  as LOCATION_PTR_FROM,PACKING_SLIP_FLAG,QUAN_STOCKED,
QUAN_ISSUED_TO_FACT,QUAN_RTNED_FM_FACT,data0022.QUAN_ON_HAND,BARCODE_ID,EXPIRE_DATE,SUPPLIER2,TAX_2,
case when tax_price IS null then 0 else tax_price end as tax_price
 from [192.168.1.253].[sj_v20_live].[dbo].data0022  inner join [192.168.1.253].[sj_v20_live].[dbo].data0017 on 
 data0022.INVENTORY_PTR=data0017.RKEY 
 where GRN_PTR in (select RKEY  from Data0456) 
 
 SET IDENTITY_INSERT data0022 off
 
 
 
 select * from [192.168.1.253].[sj_v20_live].[dbo].data0022 where  QUAN_ON_HAND>0
  
 select * from data0022 where  QUAN_ON_HAND>0
  
  
  

 
   

  

SET IDENTITY_INSERT data0058 on
insert into data0058(   RKEY,MRB_NO,WO_PTR,TRAN_PTR,DEPT_PTR,REJECT_PTR,QTY_ORG_REJ,
QTY_REJECT,PANELS,BOM_PTR,FLOW_NO,STEP,EMPL_PTR,TDATETIME,AUDIT_EMPL_PTR,
AUDIT_DATETIME,RESP_DEPT_PTR,REFERENCE,TTYPE,warehouse_ptr)
 select  data0058.RKEY,MRB_NO,WO_PTR,TRAN_PTR,Data0034.DEPT_PTR,REJECT_PTR,QTY_ORG_REJ,
QTY_REJECT,PANELS,BOM_PTR,FLOW_NO,STEP,EMPL_PTR,TDATETIME,AUDIT_EMPL_PTR,
AUDIT_DATETIME,RESP_DEPT_PTR,REFERENCE,data0058.TTYPE,2 as warehouse_ptr
from [192.168.1.253].sj_v20_live.dbo.data0058 
left join [192.168.1.253].sj_v20_live.dbo.data0034  on data0034.RKEY =data0058.dept_ptr
where WO_PTR in (select RKEY from Data0006)  and REJECT_PTR in (select RKEY from Data0039)

select current_timestamp as vdt

select * from data0604 

SET FMTONLY ON select current_timestamp as vdt
 WHERE 1=2  SET FMTONLY OFF
 
SET IDENTITY_INSERT data0604 off
insert into data0604( 
 RKEY,
TTYPE,
QUERY_NO,
QUERY_NAME,
QUERY_DESC,
QUERY_SQL_TEXT,
CREATE_EMPL_PTR,
CREATE_DATE,
UPDATE_EMPL_PTR,
UPDATE_DATE,
ACTIVE_FLAG,
BASE_DATERANGE_FLAG,
BASE_DATERANGE_DESC,
REMARK,
QUERY_TTYPE,
BASE_NOWHERE_FLAG,
DYNA_FIELD_FLAG,
GROUP_DESC,
RSTGRID_FIXCOLS,
VD1RG,
VD2RG,
VD1TIME,
VD2TIME)
select * from [192.168.1.253].[sj_v20_live].dbo.data0604