SET IDENTITY_INSERT data0017 ON
insert into Data0017( RKEY,INV_PART_NUMBER,INV_NAME,INV_DESCRIPTION,
GROUP_PTR,P_M,S_B_N,INSPECT,STOP_PURCH,MIX_PARTS,PHY_COUNT_METHOD,BOM_FLAG,COST_METHOD,
STOCK_UNIT_PTR,PURCH_UNIT_PTR,PREF_SUPPLIER_PTR,STOCK_PURCH,STOCK_QUOTE,STD_COST,SHELF_LIFE,AVL_FLAG,
CONSIGNMENT_FLAG,ACTIVE_FLAG,QUAN_ON_HAND,QUAN_ASSIGN,AUTO_PURCHASE_FLAG ,CRITICAL_MATL_FLAG)
select RKEY,INV_PART_NUMBER,INV_NAME,INV_DESCRIPTION,
GROUP_PTR,P_M,S_B_N,INSPECT,STOP_PURCH,MIX_PARTS,PHY_COUNT_METHOD,BOM_FLAG,COST_METHOD,
STOCK_UNIT_PTR,PURCH_UNIT_PTR,PREF_SUPPLIER_PTR,STOCK_PURCH,STOCK_QUOTE,STD_COST,SHELF_LIFE,AVL_FLAG,
CONSIGNMENT_FLAG,ACTIVE_FLAG,QUAN_ON_HAND,QUAN_ASSIGN,0 as AUTO_PURCHASE_FLAG,0 as CRITICAL_MATL_FLAG from [192.168.1.253].sj_v20_live.dbo.data0017 as KD0017
WHERE NOT EXISTS(SELECT RKEY FROM Data0017  WHERE Data0017.RKEY=KD0017.RKEY)
go
set identity_insert data0017 off



SET IDENTITY_INSERT data0028 ON
insert into Data0028 (RKEY,SUPPLIER_PTR,INVENTORY_PTR,EMPLOYEE_PTR,CSI_USER_PTR,TDATE,SUPPLIER_PART_NO,
LEAD_TIME,AMT_QUAN_FLAG,TAX_1,TAX_2,PRICE_1,PRICE_2,PRICE_3,PRICE_4,PRICE_5,PRICE_6,
DISC_1,DISC_2,DISC_3,DISC_4,DISC_5,DISC_6,TAX_3,TAX_4,PURCHASE_UNIT_PTR,CONVERSION_FACTOR,
AVL_FLAG,CURRENCY_PTR,EDI_OUT_FORCST,qte_price,tax_flag,qte_price2,QTE_PRICE1,SUGG_REORDER_QTY,
MIN_ORDER_QTY,MIN_ORDER_AMT,QUAN_VOL_1,QUAN_VOL_2,QUAN_VOL_3,QUAN_VOL_4,QUAN_VOL_5)
select RKEY,SUPPLIER_PTR,INVENTORY_PTR, case when EMPLOYEE_PTR in (23,29,15)   then 1 else EMPLOYEE_PTR end  as EMPLOYEE_PTR  ,CSI_USER_PTR,TDATE,SUPPLIER_PART_NO,
LEAD_TIME,AMT_QUAN_FLAG,TAX_1,TAX_2,PRICE_1,PRICE_2,PRICE_3,PRICE_4,PRICE_5,PRICE_6,
DISC_1,DISC_2,DISC_3,DISC_4,DISC_5,DISC_6,TAX_3,TAX_4,PURCHASE_UNIT_PTR,CONVERSION_FACTOR,
AVL_FLAG,CURRENCY_PTR,EDI_OUT_FORCST,qte_price,tax_flag,qte_price2,QTE_PRICE1,0 as SUGG_REORDER_QTY,
 0 as MIN_ORDER_QTY,0 as MIN_ORDER_AMT, QUAN_VOL_1,QUAN_VOL_2,QUAN_VOL_3,QUAN_VOL_4,QUAN_VOL_5
  from [192.168.1.253].sj_v20_live.dbo.data0028 as kd0028
WHERE NOT EXISTS(SELECT RKEY FROM Data0028  WHERE Data0028.RKEY=KD0028.RKEY)

go
SET IDENTITY_INSERT data0028 off


SET IDENTITY_INSERT data0023 ON
insert into Data0023(RKEY,CODE,SUPPLIER_NAME,ABBR_NAME,BILLING_ADDRESS_1,STATE,ZIP,PHONE,FAX,
TELEX,CURRENCY_PTR,PO_NOTE_PAD_PTR,DEBMEM_NOTE_PAD_PTR,RFQ_NOTE_PAD_PTR,common_pad_ptr,CONTACT_NAME_1,
CONTACT_NAME_2,CONTACT_NAME_3,CONTACT_NAME_4,CONTACT_NAME_5,CONTACT_NAME_6,CONT_PHONE_1,
CONT_PHONE_2,CONT_PHONE_3,CONT_PHONE_4,CONT_PHONE_5,CONT_PHONE_6,TAX_1,TAX_2,CURRENT_BALANCE,
OUTSTANDING_DEBITS,PAYMENT_TERMS,DISCOUNT,DISCOUNT_DAYS,PRNT_ONE_INV_PER_CHK,PUT_ALL_INV_HOLD,
LANGUAGE_FLAG,TAX_ID_NUMBER,DISCOUNT2,DISCOUNT2_DAYS,COUNTRY_PTR,NAME_FOR_FORM,ADDRESS1_FOR_FORM,
ADDRESS2_FOR_FORM,ADDRESS3_FOR_FORM,ANALYSIS_CODE1,ANALYSIS_CODE2,ANALYSIS_CODE3,SUPPIER_ENT_DATE,
EDI_ID,EDI_FLAG_FOR_PO,EDI_FLAG_DEBIT_MEMO,GEN_EMAIL_ADDRESS,EMAIL_FOR_CONTACT1,EMAIL_FOR_CONTACT2,
EMAIL_FOR_CONTACT3,EMAIL_FOR_CONTACT4,EMAIL_FOR_CONTACT5,EMAIL_FOR_CONTACT6,ACC_PAYABLE_PTR,
EDI_OUT_NEW_PO,EDI_OUT_CHG_PO,ttype,brother_flag,status)
select RKEY,CODE,SUPPLIER_NAME,ABBR_NAME,BILLING_ADDRESS_1,STATE,ZIP,PHONE,FAX,
TELEX,CURRENCY_PTR,PO_NOTE_PAD_PTR,DEBMEM_NOTE_PAD_PTR,RFQ_NOTE_PAD_PTR,common_pad_ptr,CONTACT_NAME_1,
CONTACT_NAME_2,CONTACT_NAME_3,CONTACT_NAME_4,CONTACT_NAME_5,CONTACT_NAME_6,CONT_PHONE_1,
CONT_PHONE_2,CONT_PHONE_3,CONT_PHONE_4,CONT_PHONE_5,CONT_PHONE_6,TAX_1,TAX_2,CURRENT_BALANCE,
OUTSTANDING_DEBITS,PAYMENT_TERMS,DISCOUNT,DISCOUNT_DAYS,PRNT_ONE_INV_PER_CHK,PUT_ALL_INV_HOLD,
LANGUAGE_FLAG,TAX_ID_NUMBER,DISCOUNT2,DISCOUNT2_DAYS,COUNTRY_PTR,NAME_FOR_FORM,ADDRESS1_FOR_FORM,
ADDRESS2_FOR_FORM,ADDRESS3_FOR_FORM,ANALYSIS_CODE1,ANALYSIS_CODE2,ANALYSIS_CODE3,SUPPIER_ENT_DATE,
EDI_ID,EDI_FLAG_FOR_PO,EDI_FLAG_DEBIT_MEMO,GEN_EMAIL_ADDRESS,EMAIL_FOR_CONTACT1,EMAIL_FOR_CONTACT2,
EMAIL_FOR_CONTACT3,EMAIL_FOR_CONTACT4,EMAIL_FOR_CONTACT5,EMAIL_FOR_CONTACT6,ACC_PAYABLE_PTR,
EDI_OUT_NEW_PO,EDI_OUT_CHG_PO,ttype,brother_flag,IsBad as status from [192.168.1.253].sj_v20_live.dbo.data0023 AS KD0023
 where NOT EXISTS(SELECT RKEY FROM Data0023 WHERE Data0023.RKEY=KD0023.RKEY)
 go
 SET IDENTITY_INSERT data0023 off
 
 
 
SET IDENTITY_INSERT data0024 ON
insert into Data0024( RKEY,SUPPLIER_PTR,FACTORY_LOCATION,FACTORY_ADDRESS_1,FACTORY_ADDRESS_2,FACTORY_ADDRESS_3,
STATE,ZIP,CONTACT,PHONE,FAX,FOB,CITY_TAX_PTR,SHIPPING_METHOD,SHIPPING_LEAD_TIME,STATE_SHIP_TAX_FLAG,
STATE_MISC_TAX_FLAG,STATE_INVT_TAX_FLAG,TAX_ON_TAX,LANGUAGE_FLAG,COUNTRY_PTR,LOC_NAME_FOR_FORM,
LOC_ADDR1_FOR_FORM,LOC_ADDR2_FOR_FORM,LOC_ADDR3_FOR_FORM,LOC_ANALYSIS_CODE1,LOC_ANALYSIS_CODE2,
LOC_ANALYSIS_CODE3,EMAIL_FOR_CONTACT) 
select RKEY,SUPPLIER_PTR,FACTORY_LOCATION,FACTORY_ADDRESS_1,FACTORY_ADDRESS_2,FACTORY_ADDRESS_3,
STATE,ZIP,CONTACT,PHONE,FAX,FOB,CITY_TAX_PTR,SHIPPING_METHOD,SHIPPING_LEAD_TIME,STATE_SHIP_TAX_FLAG,
STATE_MISC_TAX_FLAG,STATE_INVT_TAX_FLAG,TAX_ON_TAX,LANGUAGE_FLAG,COUNTRY_PTR,LOC_NAME_FOR_FORM,
LOC_ADDR1_FOR_FORM,LOC_ADDR2_FOR_FORM,LOC_ADDR3_FOR_FORM,LOC_ANALYSIS_CODE1,LOC_ANALYSIS_CODE2,
LOC_ANALYSIS_CODE3,EMAIL_FOR_CONTACT from [192.168.1.253].sj_v20_live.dbo.data0024 as KD0024
 where NOT EXISTS(SELECT RKEY FROM Data0024 WHERE Data0024.RKEY=KD0024.RKEY)
 go
SET IDENTITY_INSERT data0024 off




--²É¹º¶©µ¥
SET IDENTITY_INSERT data0070 on
insert into data0070(RKEY,PO_NUMBER,CSI_USER_POINTER,EMPLOYEE_POINTER,SUPPLIER_POINTER,SUPP_FAC_ADD_PTR,
WAREHOUSE_POINTER,EDIT_BY_EMPL_PTR,STATUS,EXCHANGE_RATE,SHIPPING_COST,FEDERAL_TAX,STATE_TAX,
SUB_TOTAL,CONFIRMATION_NUMBER,SHIPPING_METHOD,PO_DATE,SUPPIER_CONTACT,CONTACT_PHONE,DISCOUNT_AMOUNT,
DATE_EDITED,PO_TYPE,FOB,MISC_CHARGE,PRINT_DATE,PRINT_TIME,MULTIPLE_FACTOR,CITY_AMOUNT,COUNTY_AMOUNT,
COLLECT_PREPAID,STATE_SHIP_TAX_FLAG,STATE_MISC_TAX_FLAG,STATE_INVT_TAX_FLAG,CURRENCY_PTR,
SECOND_WHSE_PTR,PO_REV_NO,PAYMENT_TERMS,CASH_DISCOUNT,DISCOUNT_DAYS,CASH_DISCOUNT2,DISCOUNT2_DAYS,
PURCHASE_ORDER_TYPE,EXPIRED_DATE,ANALYSIS_CODE_1,ANALYSIS_CODE_2,ANALYSIS_CODE_3,ANALYSIS_CODE_4,
ANALYSIS_CODE_5)
select RKEY,PO_NUMBER,CSI_USER_POINTER,EMPLOYEE_POINTER,SUPPLIER_POINTER,SUPP_FAC_ADD_PTR,
WAREHOUSE_POINTER,EDIT_BY_EMPL_PTR,STATUS,EXCHANGE_RATE,SHIPPING_COST,FEDERAL_TAX,STATE_TAX,
SUB_TOTAL,CONFIRMATION_NUMBER,SHIPPING_METHOD,PO_DATE,SUPPIER_CONTACT,CONTACT_PHONE,DISCOUNT_AMOUNT,
DATE_EDITED,PO_TYPE,FOB,MISC_CHARGE,PRINT_DATE,PRINT_TIME,MULTIPLE_FACTOR,CITY_AMOUNT,COUNTY_AMOUNT,
COLLECT_PREPAID,STATE_SHIP_TAX_FLAG,STATE_MISC_TAX_FLAG,STATE_INVT_TAX_FLAG,CURRENCY_PTR,
SECOND_WHSE_PTR,PO_REV_NO,PAYMENT_TERMS,CASH_DISCOUNT,DISCOUNT_DAYS,CASH_DISCOUNT2,DISCOUNT2_DAYS,
PURCHASE_ORDER_TYPE,EXPIRED_DATE,ANALYSIS_CODE_1,ANALYSIS_CODE_2,ANALYSIS_CODE_3,ANALYSIS_CODE_4,
ANALYSIS_CODE_5 from [192.168.1.253].sj_v20_live.dbo.data0070  
 where (PO_DATE>='2016-01-01'  or rkey in(select  rkey from [192.168.1.253].sj_v20_live.dbo.Data0070 where PO_DATE<'2016-01-01'  and rkey in(
select PO_PTR from [192.168.1.253].sj_v20_live.dbo.Data0071 where RKEY in(
select SOURCE_PTR from [192.168.1.253].sj_v20_live.dbo.Data0022 where QUAN_ON_HAND>0 and SOURCE_PTR is not null))))
and  data0070.PO_TYPE in('M','S')
 
SET IDENTITY_INSERT data0070 off

--delete from data0070
--delete from data0071
--delete from data0456
--delete from data0022



select RKEY,PO_PTR,INVT_PTR,QUAN_ORD,QUAN_RECD,QUAN_IN_INSP,QUAN_RETN,QUAN_INVD,PRICE,TAX_2,
DISCOUNT,recd_DATE,REQ_DATE,QUAN_REJD,PURCHASE_UNIT_PTR,CONVERSION_FACTOR,
reason,extra_req,avl_flag,tax_price from [192.168.1.253].sj_v20_live.dbo.data0071 
where PO_PTR in (select RKEY from Data0070)


SET IDENTITY_INSERT data0071 on
insert into data0071( RKEY,PO_PTR,INVT_PTR,QUAN_ORD,QUAN_RECD,QUAN_IN_INSP,QUAN_RETN,QUAN_INVD,PRICE,TAX_2,
DISCOUNT,recd_DATE,REQ_DATE,QUAN_REJD,PURCHASE_UNIT_PTR,CONVERSION_FACTOR,
reason,extra_req,avl_flag,tax_price,WO_PTR )
select  data0071.RKEY,PO_PTR,INVT_PTR,QUAN_ORD,QUAN_RECD, 0 as QUAN_IN_INSP,QUAN_RETN,QUAN_INVD,data0071.PRICE,data0071.TAX_2,
data0071.DISCOUNT,recd_DATE,REQ_DATE,QUAN_ORD as   QUAN_REJD,PURCHASE_UNIT_PTR,CONVERSION_FACTOR,
reason,data0071.extra_req,  'N'  as AVL_FLAG,data0071.tax_price,PURCHASE_UNIT_PTR as WO_PTR from [192.168.1.253].sj_v20_live.dbo.data0071
left join [192.168.1.253].sj_v20_live.dbo.data0017 on data0071.INVT_PTR=data0017.RKEY 
where (PO_PTR in (select RKEY from Data0070)  or PO_PTR in(select  rkey from [192.168.1.253].sj_v20_live.dbo.Data0070 where PO_DATE<'2016-01-01'  and rkey in(
select PO_PTR from [192.168.1.253].sj_v20_live.dbo.Data0071 where RKEY in(
select SOURCE_PTR from [192.168.1.253].sj_v20_live.dbo.Data0022 where QUAN_ON_HAND>0 and SOURCE_PTR is not null))))
and PO_PTR in(select RKEY from Data0070 where PO_TYPE in ('M','S')) 

go

SET IDENTITY_INSERT data0071 off






--delete from Data0071
--delete from Data0022

select * from Data0022 